Disadvantages of numpy:
Numpy don't have any labels. --> arr=np.array([22,21,34,56])
It doesn't have any label like it is a list of ages in numpy.
Without any information it is difficult for us to analyze what data it is.
But if it is in the form of tables with rows and columns, it will be easy for us to analyze the data.

PANDAS  (Alias name of pandas is pd)
WES MCKINNEY felt difficult while analyzing the financial datas. So he built pandas on top of numpy. 
The raw datas are arranged in tabular form and labels are given to it.Pandas was released in 2009.

Python-->Gives only raw data
Numpy -->Datas only in the form of numbers
Pandas-->Data is present in the table and every data should have label so that we can analyze it in a better way.

In [ ]:
DATAFRAME ---> CLASS inside pandas library

import pandas
df=pandas.DataFrame()  #Since it is a class, object has been created and reference is given to it.
#This only creates the table without any datas and labels inside it.

data={
    'Name':["Tim","Raj","Rishi","Nithish"],  #Multiple datas given inside list and every fature of list can be accessed here like duplicate values,heterogenous datas,etc
    'Age':[25,49,21,25]
}

In [3]:
import pandas
data={
    'Name':["Tim","Raj","Rishi","Nithish"],  #Multiple datas given inside list and every fature of list can be accessed here like duplicate values,heterogenous datas,etc
    'Age':[25,49,21,25]
}
df=pandas.DataFrame(data) #In pandas we should not tell as table, it is called "DataFrame".
print(df)   #In the output, the indexes would start from 0 as default.

      Name  Age
0      Tim   25
1      Raj   49
2    Rishi   21
3  Nithish   25

In [15]:
import pandas as pd
data={
    "id" : [1,2,3,4,5,6,7,8],
    "Name" : ['Kshitij','Sharath','Somanna','Poovizhi','Kshitij','Sharath','Somanna','Poovizhi'],
    "Salary" : [1000000,20000,34384,23950,1000000,20000,34384,23950],
    "Dept" : ['IT',"SALES","FIN","HR",'IT',"SALES","FIN","HR"]
    }
df=pd.DataFrame(data)
print(df)

#or

df=pd.DataFrame({
    "id" : [1,2,3,4,5,6,7,8],
    "Name" : ['Kshitij','Sharath','Somanna','Poovizhi','Kshitij','Sharath','Somanna','Poovizhi'],
    "Salary" : [1000000,20000,34384,23950,1000000,20000,34384,23950],
    "Dept" : ['IT',"SALES","FIN","HR",'IT',"SALES","FIN","HR"]
    })
print(df)

   id      Name   Salary   Dept
0   1   Kshitij  1000000     IT
1   2   Sharath    20000  SALES
2   3   Somanna    34384    FIN
3   4  Poovizhi    23950     HR
4   5   Kshitij  1000000     IT
5   6   Sharath    20000  SALES
6   7   Somanna    34384    FIN
7   8  Poovizhi    23950     HR
   id      Name   Salary   Dept
0   1   Kshitij  1000000     IT
1   2   Sharath    20000  SALES
2   3   Somanna    34384    FIN
3   4  Poovizhi    23950     HR
4   5   Kshitij  1000000     IT
5   6   Sharath    20000  SALES
6   7   Somanna    34384    FIN
7   8  Poovizhi    23950     HR

PICKING OF DATA - Before analyzing the data it is very importatnt
When we perform the below 5 things in pandas then it is called as EXPLORATORY DATA ANALYSIS (EDA)
1.info()
2.head()
3.tail()
4.shape
5.describe()

In [16]:
#There is a method in pandas called as info() - which gives the entire information about the dataframe that is present inside the object
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      8 non-null      int64
 1   Name    8 non-null      object
 2   Salary  8 non-null      int64
 3   Dept    8 non-null      object
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes

In [17]:
#head() - This is method in pandas to get the first 5 rows of the dataframe to analyze instead of getting crores of rows present in the table which would be easy to analyze.

df.head()

   id      Name   Salary   Dept
0   1   Kshitij  1000000     IT
1   2   Sharath    20000  SALES
2   3   Somanna    34384    FIN
3   4  Poovizhi    23950     HR
4   5   Kshitij  1000000     IT

In [18]:
#tail() - This is method in pandas to get the last 5 rows of the dataframe to analyze instead of getting crores of rows present in the table which would be easy to analyze.

df.tail()

   id      Name   Salary   Dept
3   4  Poovizhi    23950     HR
4   5   Kshitij  1000000     IT
5   6   Sharath    20000  SALES
6   7   Somanna    34384    FIN
7   8  Poovizhi    23950     HR

In [19]:
#Shape is an instance variable in pandas which tells the no.of rows and columns present in the dataframe. (rows,cols)
df.shape

(8, 4)

In [20]:
#describe() -- Describe is a method that is used for statistical analysis of numerical columns present in the dataframe.
df.describe()

            id          Salary
count  8.00000        8.000000
mean   4.50000   269583.500000
std    2.44949   450857.851551
min    1.00000    20000.000000
25%    2.75000    22962.500000
50%    4.50000    29167.000000
75%    6.25000   275788.000000
max    8.00000  1000000.000000

SERIES --> It is also a class in pandas.
Series is one strip of data which is called as Vector in Numpy.
DataFrame is with rows and columns in pandas which is called as matrice in Numpy.

In [6]:
#Series -->falls on 1D array (1 piece of data)
import pandas as pd
s=pd.Series(data=[22,23,24,25,78])
print(s) #Index starts with 0 by default

0    22
1    23
2    24
3    25
4    78
dtype: int64

In [8]:
#We can also specify our own index
import pandas as pd
s=pd.Series(data=[22,23,24,25,78],index=["Tim","Alex","Raju","Diya","Khamal"])
print(s)

Tim       22
Alex      23
Raju      24
Diya      25
Khamal    78
dtype: int64