In [7]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\rankings.csv")
print(df)

     2025 Rank  2024 Rank                              Institution Name  \
0            1          1  Massachusetts Institute of Technology (MIT)
1            2          6                       Imperial College London
2            3          3                          University of Oxford
3            4          4                            Harvard University
4            5          2                       University of Cambridge
...        ...        ...                                           ...
1498     1401+  1201-1400               University of Montana Missoula
1499     1401+      1401+                          University of Oradea
1500     1401+  1201-1400                      University of San Carlos
1501     1401+      1401+      University Politehnica of Timisoara, UPT
1502     1401+      1401+                 Western Washington University

     Location   Location Full Size  Academic Reputation  Employer Reputation  \
0          US   United States    M                100.0                100.0
1          UK  United Kingdom    L                 98.5                 99.5
2          UK  United Kingdom    L                100.0                100.0
3          US   United States    L                100.0                100.0
4          UK  United Kingdom    L                100.0                100.0
...       ...             ...  ...                  ...                  ...
1498       US   United States    M                  3.0                  2.2
1499       RO         Romania    L                  5.6                  2.2
1500       PH     Philippines    M                  7.2                  9.4
1501       RO         Romania    L                  4.1                  4.2
1502       US   United States    L                  2.6                  2.6

      Faculty Student  Citations per Faculty  International Faculty  \
0               100.0                  100.0                   99.3
1                98.2                   93.9                  100.0
2               100.0                   84.8                   98.1
3                96.3                  100.0                   74.1
4               100.0                   84.6                  100.0
...               ...                    ...                    ...
1498             10.6                    6.1                    1.3
1499              4.0                    1.9                    1.5
1500              3.3                    1.8                    2.1
1501              7.2                    3.9                    1.4
1502              7.3                    3.5                    9.7

      International Students  International Research Network  \
0                       86.8                            96.0
1                       99.6                            97.4
2                       97.7                           100.0
3                       69.0                            99.6
4                       94.8                            99.3
...                      ...                             ...
1498                     1.9                             6.5
1499                     5.2                            34.5
1500                     2.1                             6.4
1501                     2.5                            18.6
1502                     1.6                            12.4

      Employment Outcomes  Sustainability QS Overall Score
0                   100.0            99.0              100
1                    93.4            99.7             98.5
2                   100.0            85.0             96.9
3                   100.0            84.4             96.8
4                   100.0            84.8             96.7
...                   ...             ...              ...
1498                  3.1             1.0                -
1499                  6.2             2.3                -
1500                  9.6             1.0                -
1501                  3.9             1.1                -
1502                  1.5             1.1                -

[1503 rows x 16 columns]

In [8]:
print(df.head())

  2025 Rank 2024 Rank                              Institution Name Location  \
0         1         1  Massachusetts Institute of Technology (MIT)        US
1         2         6                       Imperial College London       UK
2         3         3                          University of Oxford       UK
3         4         4                            Harvard University       US
4         5         2                       University of Cambridge       UK

    Location Full Size  Academic Reputation  Employer Reputation  \
0   United States    M                100.0                100.0
1  United Kingdom    L                 98.5                 99.5
2  United Kingdom    L                100.0                100.0
3   United States    L                100.0                100.0
4  United Kingdom    L                100.0                100.0

   Faculty Student  Citations per Faculty  International Faculty  \
0            100.0                  100.0                   99.3
1             98.2                   93.9                  100.0
2            100.0                   84.8                   98.1
3             96.3                  100.0                   74.1
4            100.0                   84.6                  100.0

   International Students  International Research Network  \
0                    86.8                            96.0
1                    99.6                            97.4
2                    97.7                           100.0
3                    69.0                            99.6
4                    94.8                            99.3

   Employment Outcomes  Sustainability QS Overall Score
0                100.0            99.0              100
1                 93.4            99.7             98.5
2                100.0            85.0             96.9
3                100.0            84.4             96.8
4                100.0            84.8             96.7

In [9]:
df.tail()

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
1498,1401+,1201-1400,University of Montana Missoula,US,United States,M,3.0,2.2,10.6,6.1,1.3,1.9,6.5,3.1,1.0,-
1499,1401+,1401+,University of Oradea,RO,Romania,L,5.6,2.2,4.0,1.9,1.5,5.2,34.5,6.2,2.3,-
1500,1401+,1201-1400,University of San Carlos,PH,Philippines,M,7.2,9.4,3.3,1.8,2.1,2.1,6.4,9.6,1.0,-
1501,1401+,1401+,"University Politehnica of Timisoara, UPT",RO,Romania,L,4.1,4.2,7.2,3.9,1.4,2.5,18.6,3.9,1.1,-
1502,1401+,1401+,Western Washington University,US,United States,L,2.6,2.6,7.3,3.5,9.7,1.6,12.4,1.5,1.1,-

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   2025 Rank                       1503 non-null   object
 1   2024 Rank                       1482 non-null   object
 2   Institution Name                1503 non-null   object
 3   Location                        1503 non-null   object
 4   Location Full                   1503 non-null   object
 5   Size                            1503 non-null   object
 6   Academic Reputation             1503 non-null   float64
 7   Employer Reputation             1503 non-null   float64
 8   Faculty Student                 1503 non-null   float64
 9   Citations per Faculty           1503 non-null   float64
 10  International Faculty           1403 non-null   float64
 11  International Students          1445 non-null   float64
 12  International Research Network  1502 non-null   float64
 13  Employment Outcomes             1503 non-null   float64
 14  Sustainability                  1484 non-null   float64
 15  QS Overall Score                1503 non-null   object
dtypes: float64(9), object(7)
memory usage: 188.0+ KB

In [11]:
df.describe()

,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability
count,1503.00000,1503.000000,1503.000000,1503.000000,1403.000000,1445.000000,1502.000000,1503.000000,1484.000000
mean,20.28656,19.786693,28.128676,23.503460,30.725374,25.580346,50.129095,23.825083,24.309299
std,22.32623,23.784986,27.613017,27.870692,34.328935,31.098689,29.866588,27.351315,31.074718
min,1.30000,1.100000,1.000000,1.000000,1.000000,1.000000,1.000000,1.200000,1.000000
25%,6.30000,4.300000,7.300000,2.800000,4.200000,2.900000,22.725000,4.000000,1.300000
50%,11.00000,9.400000,16.000000,9.900000,12.500000,9.600000,51.100000,11.800000,6.750000
75%,23.50000,25.300000,40.400000,36.400000,51.600000,38.300000,77.100000,33.400000,39.500000
max,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [12]:
df.shape

(1503, 16)

In [13]:
df.dtypes

2025 Rank                          object
2024 Rank                          object
Institution Name                   object
Location                           object
Location Full                      object
Size                               object
Academic Reputation               float64
Employer Reputation               float64
Faculty Student                   float64
Citations per Faculty             float64
International Faculty             float64
International Students            float64
International Research Network    float64
Employment Outcomes               float64
Sustainability                    float64
QS Overall Score                   object
dtype: object

In [17]:
print(df["Size"])

0       M
1       L
2       L
3       L
4       L
       ..
1498    M
1499    L
1500    M
1501    L
1502    L
Name: Size, Length: 1503, dtype: object

In [19]:
print(df[["Employment Outcomes","QS Overall Score"]])

      Employment Outcomes QS Overall Score
0                   100.0              100
1                    93.4             98.5
2                   100.0             96.9
3                   100.0             96.8
4                   100.0             96.7
...                   ...              ...
1498                  3.1                -
1499                  6.2                -
1500                  9.6                -
1501                  3.9                -
1502                  1.5                -

[1503 rows x 2 columns]

In [21]:
print(df.loc[456])

2025 Rank                                     456
2024 Rank                                     465
Institution Name                  Umea University
Location                                       SE
Location Full                              Sweden
Size                                            L
Academic Reputation                          19.9
Employer Reputation                          11.6
Faculty Student                              71.8
Citations per Faculty                        15.2
International Faculty                        51.1
International Students                       21.8
International Research Network               78.0
Employment Outcomes                           9.0
Sustainability                               26.3
QS Overall Score                             26.3
Name: 456, dtype: object

In [22]:
print(df.iloc[345])

2025 Rank                                        344
2024 Rank                                        313
Institution Name                  University of Oulu
Location                                          FI
Location Full                                Finland
Size                                               M
Academic Reputation                             15.1
Employer Reputation                             13.5
Faculty Student                                 25.3
Citations per Faculty                           59.4
International Faculty                           65.3
International Students                           8.6
International Research Network                  89.4
Employment Outcomes                             21.7
Sustainability                                  68.6
QS Overall Score                                32.9
Name: 345, dtype: object

In [25]:
print(df.loc[456:789:3])

    2025 Rank 2024 Rank                                   Institution Name  \
456       456       465                                    Umea University
459       460       396  Stony Brook University, State University of Ne...
462       462       494                             Universidad de Sevilla
465       466       478                               Universität Konstanz
468       466       419                        Washington State University
..        ...       ...                                                ...
777   771-780  951-1000                       Université de Tunis El Manar
780   771-780   801-850                                  Verona University
783   781-790       NaN                  National University of Uzbekistan
786   781-790   641-650                                     The New School
789   781-790   801-850                               University of Latvia

    Location  Location Full Size  Academic Reputation  Employer Reputation  \
456       SE         Sweden    L                 19.9                 11.6
459       US  United States    L                 18.0                  7.3
462       ES          Spain   XL                 39.1                 12.6
465       DE        Germany    M                 18.3                 10.5
468       US  United States    L                 23.3                 20.0
..       ...            ...  ...                  ...                  ...
777       TN        Tunisia    L                  9.4                  4.3
780       IT          Italy    L                  9.1                  2.7
783       UZ     Uzbekistan    L                 25.5                 15.8
786       US  United States    M                 15.2                  8.2
789       LV         Latvia    L                 11.5                 16.7

     Faculty Student  Citations per Faculty  International Faculty  \
456             71.8                   15.2                   51.1
459             32.2                   23.6                   34.7
462             18.4                    8.2                    3.5
465             37.8                   18.3                   85.9
468             15.5                   33.5                   47.1
..               ...                    ...                    ...
777             26.0                    5.1                   39.5
780              4.1                   41.6                    4.5
783              5.2                    1.3                   89.0
786             41.1                    2.6                    5.7
789              5.9                    5.3                   12.1

     International Students  International Research Network  \
456                    21.8                            78.0
459                    43.5                            76.0
462                    18.9                            91.4
465                    14.5                            66.1
468                     5.0                            77.3
..                      ...                             ...
777                     7.8                            82.1
780                     4.2                            71.0
783                     2.5                            11.8
786                    92.3                            19.6
789                     5.1                            71.5

     Employment Outcomes  Sustainability QS Overall Score
456                  9.0            26.3             26.3
459                 21.2            79.1             26.2
462                 16.0            67.4               26
465                 13.1            63.1             25.7
468                  8.6            29.6             25.7
..                   ...             ...              ...
777                 54.1            16.3                -
780                  3.1            22.5                -
783                 20.4             1.4                -
786                 13.5             1.0                -
789                 90.4             9.8                -

[112 rows x 16 columns]

In [26]:
print(df.iloc[456:789:3])

    2025 Rank 2024 Rank                                   Institution Name  \
456       456       465                                    Umea University
459       460       396  Stony Brook University, State University of Ne...
462       462       494                             Universidad de Sevilla
465       466       478                               Universität Konstanz
468       466       419                        Washington State University
..        ...       ...                                                ...
774   771-780   681-690                                  Colegio de México
777   771-780  951-1000                       Université de Tunis El Manar
780   771-780   801-850                                  Verona University
783   781-790       NaN                  National University of Uzbekistan
786   781-790   641-650                                     The New School

    Location  Location Full Size  Academic Reputation  Employer Reputation  \
456       SE         Sweden    L                 19.9                 11.6
459       US  United States    L                 18.0                  7.3
462       ES          Spain   XL                 39.1                 12.6
465       DE        Germany    M                 18.3                 10.5
468       US  United States    L                 23.3                 20.0
..       ...            ...  ...                  ...                  ...
774       MX         Mexico    S                 14.9                  2.5
777       TN        Tunisia    L                  9.4                  4.3
780       IT          Italy    L                  9.1                  2.7
783       UZ     Uzbekistan    L                 25.5                 15.8
786       US  United States    M                 15.2                  8.2

     Faculty Student  Citations per Faculty  International Faculty  \
456             71.8                   15.2                   51.1
459             32.2                   23.6                   34.7
462             18.4                    8.2                    3.5
465             37.8                   18.3                   85.9
468             15.5                   33.5                   47.1
..               ...                    ...                    ...
774            100.0                    1.7                    8.5
777             26.0                    5.1                   39.5
780              4.1                   41.6                    4.5
783              5.2                    1.3                   89.0
786             41.1                    2.6                    5.7

     International Students  International Research Network  \
456                    21.8                            78.0
459                    43.5                            76.0
462                    18.9                            91.4
465                    14.5                            66.1
468                     5.0                            77.3
..                      ...                             ...
774                    16.4                             9.6
777                     7.8                            82.1
780                     4.2                            71.0
783                     2.5                            11.8
786                    92.3                            19.6

     Employment Outcomes  Sustainability QS Overall Score
456                  9.0            26.3             26.3
459                 21.2            79.1             26.2
462                 16.0            67.4               26
465                 13.1            63.1             25.7
468                  8.6            29.6             25.7
..                   ...             ...              ...
774                  3.2             1.0                -
777                 54.1            16.3                -
780                  3.1            22.5                -
783                 20.4             1.4                -
786                 13.5             1.0                -

[111 rows x 16 columns]

In [28]:
df["Size"]=="L"

0       False
1        True
2        True
3        True
4        True
        ...
1498    False
1499     True
1500    False
1501     True
1502     True
Name: Size, Length: 1503, dtype: bool

In [31]:
df[df["Size"]=="L"]

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
1,2,6,Imperial College London,UK,United Kingdom,L,98.5,99.5,98.2,93.9,100.0,99.6,97.4,93.4,99.7,98.5
2,3,3,University of Oxford,UK,United Kingdom,L,100.0,100.0,100.0,84.8,98.1,97.7,100.0,100.0,85.0,96.9
3,4,4,Harvard University,US,United States,L,100.0,100.0,96.3,100.0,74.1,69.0,99.6,100.0,84.4,96.8
4,5,2,University of Cambridge,UK,United Kingdom,L,100.0,100.0,100.0,84.6,100.0,94.8,99.3,100.0,84.8,96.7
5,6,5,Stanford University,US,United States,L,100.0,100.0,100.0,99.0,70.3,60.8,96.8,100.0,81.2,96.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1401+,1401+,University of Craiova,RO,Romania,L,4.5,2.2,3.2,2.1,NaN,NaN,21.8,13.4,1.0,-
1496,1401+,1401+,University of Lampung,ID,Indonesia,L,4.7,2.3,5.1,1.3,1.2,1.0,3.4,2.2,1.0,-
1499,1401+,1401+,University of Oradea,RO,Romania,L,5.6,2.2,4.0,1.9,1.5,5.2,34.5,6.2,2.3,-
1501,1401+,1401+,"University Politehnica of Timisoara, UPT",RO,Romania,L,4.1,4.2,7.2,3.9,1.4,2.5,18.6,3.9,1.1,-
1502,1401+,1401+,Western Washington University,US,United States,L,2.6,2.6,7.3,3.5,9.7,1.6,12.4,1.5,1.1,-

In [36]:
df[(df["Location"]=="UK") & (df["Academic Reputation"]>50.0) & (df["Employment Outcomes"]>=65.5)]

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
1,2,6,Imperial College London,UK,United Kingdom,L,98.5,99.5,98.2,93.9,100.0,99.6,97.4,93.4,99.7,98.5
2,3,3,University of Oxford,UK,United Kingdom,L,100.0,100.0,100.0,84.8,98.1,97.7,100.0,100.0,85.0,96.9
4,5,2,University of Cambridge,UK,United Kingdom,L,100.0,100.0,100.0,84.6,100.0,94.8,99.3,100.0,84.8,96.7
8,9,9,UCL,UK,United Kingdom,XL,99.5,98.3,95.9,72.2,99.0,100.0,99.9,70.3,74.8,91.6
34,34,32,The University of Manchester,UK,United Kingdom,XL,95.6,98.1,51.3,45.1,93.1,99.2,99.2,87.6,99.8,82
51,50,45,The London School of Economics and Political S...,UK,United Kingdom,L,67.2,97.0,35.1,69.4,100.0,100.0,81.2,99.6,91.3,76
68,69,67,The University of Warwick,UK,United Kingdom,L,72.2,86.4,35.5,37.7,98.1,99.1,94.2,65.7,89.7,68.2

In [38]:
df.sort_values(by="Location")

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
260,261,290,United Arab Emirates University,AE,United Arab Emirates,M,30.1,38.3,49.8,16.6,100.0,34.2,86.2,82.0,36.6,39.4
476,477,551,Ajman University,AE,United Arab Emirates,S,17.3,42.2,9.6,3.2,100.0,100.0,48.4,9.8,1.4,25.1
433,434,465,University of Sharjah,AE,United Arab Emirates,L,18.1,17.3,6.0,22.0,100.0,100.0,84.8,11.2,11.8,27.5
484,485,NaN,American University of Ras Al Khaimah ( AURAK ),AE,United Arab Emirates,S,4.6,3.3,35.5,46.8,100.0,100.0,15.4,4.1,1.1,24.8
500,501,580,Abu Dhabi University,AE,United Arab Emirates,S,15.9,24.6,14.9,16.7,100.0,99.8,27.3,8.3,1.5,24.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,851-900,801-850,North-West University,ZA,South Africa,XL,7.4,11.0,4.9,14.9,6.6,2.0,92.9,16.7,28.4,-
1187,1001-1200,1001-1200,University of the Free State,ZA,South Africa,L,6.1,5.8,3.4,8.8,NaN,4.4,92.4,11.6,1.7,-
170,171,173,University of Cape Town,ZA,South Africa,L,45.2,51.8,13.8,46.8,56.5,19.2,97.3,95.8,95.6,50
295,296,283,Stellenbosch University,ZA,South Africa,L,26.1,35.8,3.5,61.9,19.7,8.0,94.8,85.2,22.0,36.7
1002,951-1000,951-1000,University of the Western Cape,ZA,South Africa,L,8.6,5.3,4.1,14.1,25.2,3.7,76.8,21.0,2.2,-

In [39]:
df.sort_values("International Students", ascending = False)

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
25,26,36,EPFL,CH,Switzerland,M,84.2,67.2,91.2,93.6,100.0,100.0,81.7,27.2,86.7,83.5
17,18,19,The University of Sydney,AU,Australia,XL,96.4,90.0,10.9,93.7,99.9,100.0,95.8,93.1,99.6,87.3
1056,1001-1200,901-950,London Metropolitan University,UK,United Kingdom,M,5.0,3.0,3.8,3.3,59.5,100.0,16.1,13.5,1.0,-
476,477,551,Ajman University,AE,United Arab Emirates,S,17.3,42.2,9.6,3.2,100.0,100.0,48.4,9.8,1.4,25.1
51,50,45,The London School of Economics and Political S...,UK,United Kingdom,L,67.2,97.0,35.1,69.4,100.0,100.0,81.2,99.6,91.3,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1474,1401+,1201-1400,Universidad Nacional del Comahue,AR,Argentina,XL,5.1,2.4,20.4,1.3,NaN,NaN,13.1,2.1,1.2,-
1482,1401+,1201-1400,Universidad Veracruzana,MX,Mexico,XL,7.7,2.7,7.3,1.4,NaN,NaN,13.6,1.5,1.1,-
1483,1401+,1401+,Universidade do Estado de Santa Catarina,BR,Brazil,XL,3.7,1.3,15.4,1.7,NaN,NaN,9.0,2.2,1.0,-
1488,1401+,1401+,Universidade Federal do Estado do Rio de Janei...,BR,Brazil,L,2.9,2.0,8.1,2.1,NaN,NaN,8.6,1.5,1.0,-
1495,1401+,1401+,University of Craiova,RO,Romania,L,4.5,2.2,3.2,2.1,NaN,NaN,21.8,13.4,1.0,-

In [40]:
df.isnull()

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1501,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1502,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [41]:
df.isnull().sum()

2025 Rank                           0
2024 Rank                          21
Institution Name                    0
Location                            0
Location Full                       0
Size                                0
Academic Reputation                 0
Employer Reputation                 0
Faculty Student                     0
Citations per Faculty               0
International Faculty             100
International Students             58
International Research Network      1
Employment Outcomes                 0
Sustainability                     19
QS Overall Score                    0
dtype: int64