EDA on the exams.csv downloaded from Kaggle

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\exams.csv")  #This is actually we haven't created notebook in downloads, instead we created it inside python folder, so give the full path of the dataset
print(df)

     gender race/ethnicity parental level of education         lunch  \
0      male        group A                 high school      standard
1    female        group D            some high school  free/reduced
2      male        group E                some college  free/reduced
3      male        group B                 high school      standard
4      male        group E          associate's degree      standard
..      ...            ...                         ...           ...
995    male        group C                 high school      standard
996    male        group D          associate's degree  free/reduced
997  female        group C            some high school  free/reduced
998  female        group C                some college      standard
999    male        group A                some college      standard

    test preparation course  math score  reading score  writing score
0                 completed          67             67             63
1                      none          40             59             55
2                      none          59             60             50
3                      none          77             78             68
4                 completed          78             73             68
..                      ...         ...            ...            ...
995                    none          73             70             65
996               completed          85             91             92
997                    none          32             35             41
998                    none          73             74             82
999               completed          65             60             62

[1000 rows x 8 columns]

In [4]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\exams.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [5]:
print(df.head())

   gender race/ethnicity parental level of education         lunch  \
0    male        group A                 high school      standard
1  female        group D            some high school  free/reduced
2    male        group E                some college  free/reduced
3    male        group B                 high school      standard
4    male        group E          associate's degree      standard

  test preparation course  math score  reading score  writing score
0               completed          67             67             63
1                    none          40             59             55
2                    none          59             60             50
3                    none          77             78             68
4               completed          78             73             68

In [6]:
print(df.tail())

     gender race/ethnicity parental level of education         lunch  \
995    male        group C                 high school      standard
996    male        group D          associate's degree  free/reduced
997  female        group C            some high school  free/reduced
998  female        group C                some college      standard
999    male        group A                some college      standard

    test preparation course  math score  reading score  writing score
995                    none          73             70             65
996               completed          85             91             92
997                    none          32             35             41
998                    none          73             74             82
999               completed          65             60             62

In [7]:
print(df.describe())

        math score  reading score  writing score
count  1000.000000    1000.000000    1000.000000
mean     66.396000      69.002000      67.738000
std      15.402871      14.737272      15.600985
min      13.000000      27.000000      23.000000
25%      56.000000      60.000000      58.000000
50%      66.500000      70.000000      68.000000
75%      77.000000      79.000000      79.000000
max     100.000000     100.000000     100.000000

In [8]:
print(df.shape)

(1000, 8)

In [9]:
print(df.dtypes)

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [12]:
print(df['math score'])

0      67
1      40
2      59
3      77
4      78
       ..
995    73
996    85
997    32
998    73
999    65
Name: math score, Length: 1000, dtype: int64

In [14]:
print(df[['reading score','writing score']])

     reading score  writing score
0               67             63
1               59             55
2               60             50
3               78             68
4               73             68
..             ...            ...
995             70             65
996             91             92
997             35             41
998             74             82
999             60             62

[1000 rows x 2 columns]

In [22]:
print(df.loc[0])

gender                                male
race/ethnicity                     group A
parental level of education    high school
lunch                             standard
test preparation course          completed
math score                              67
reading score                           67
writing score                           63
Name: 0, dtype: object

In [17]:
print(df.loc[0:8:2])  #8 is included

   gender race/ethnicity parental level of education         lunch  \
0    male        group A                 high school      standard
2    male        group E                some college  free/reduced
4    male        group E          associate's degree      standard
6  female        group A           bachelor's degree      standard
8    male        group D                 high school      standard

  test preparation course  math score  reading score  writing score
0               completed          67             67             63
2                    none          59             60             50
4               completed          78             73             68
6                    none          62             59             63
8                    none          63             56             65

In [23]:
df.iloc[1]

gender                                   female
race/ethnicity                          group D
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   40
reading score                                59
writing score                                55
Name: 1, dtype: object

In [24]:
df.iloc[0:8:2]  #8 is excluded, goes till row 7 only

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group A,high school,standard,completed,67,67,63
2,male,group E,some college,free/reduced,none,59,60,50
4,male,group E,associate's degree,standard,completed,78,73,68
6,female,group A,bachelor's degree,standard,none,62,59,63

In [28]:
df[df["math score"] > 68]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group B,high school,standard,none,77,78,68
4,male,group E,associate's degree,standard,completed,78,73,68
7,male,group E,some college,standard,completed,93,88,84
10,male,group E,some college,standard,completed,99,83,85
11,female,group D,high school,standard,completed,80,87,90
...,...,...,...,...,...,...,...,...
992,male,group C,some college,standard,none,69,63,66
994,male,group E,high school,free/reduced,completed,86,82,75
995,male,group C,high school,standard,none,73,70,65
996,male,group D,associate's degree,free/reduced,completed,85,91,92
998,female,group C,some college,standard,none,73,74,82

In [27]:
df[(df["race/ethnicity"]=="group A") | (df["race/ethnicity"]=="group D")]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group A,high school,standard,completed,67,67,63
1,female,group D,some high school,free/reduced,none,40,59,55
5,female,group D,high school,standard,none,63,77,76
6,female,group A,bachelor's degree,standard,none,62,59,63
8,male,group D,high school,standard,none,63,56,65
...,...,...,...,...,...,...,...,...
989,male,group D,some college,standard,completed,70,60,65
990,male,group D,some college,standard,none,67,55,53
993,female,group A,associate's degree,standard,none,58,54,58
996,male,group D,associate's degree,free/reduced,completed,85,91,92
999,male,group A,some college,standard,completed,65,60,62

In [30]:
df[(df["parental level of education"]=="high school") & (df["test preparation course"]=="none") & (df["math score"]>60) & (df["math score"]<86) & (df["writing score"]>58) ]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group B,high school,standard,none,77,78,68
5,female,group D,high school,standard,none,63,77,76
8,male,group D,high school,standard,none,63,56,65
27,male,group E,high school,standard,none,71,68,60
41,male,group D,high school,standard,none,77,67,64
...,...,...,...,...,...,...,...,...
914,male,group D,high school,standard,none,77,62,65
916,male,group D,high school,standard,none,83,72,68
917,male,group E,high school,free/reduced,none,70,73,69
984,female,group D,high school,standard,none,63,71,75
995,male,group C,high school,standard,none,73,70,65

In [31]:
df.sort_values(by = "reading score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
689,male,group C,some college,free/reduced,none,36,27,26
885,male,group B,high school,free/reduced,none,37,28,23
300,male,group B,some college,free/reduced,none,43,28,24
392,female,group C,some college,free/reduced,none,13,29,23
976,female,group B,some college,free/reduced,completed,31,29,35
...,...,...,...,...,...,...,...,...
825,male,group E,associate's degree,standard,completed,100,100,100
96,female,group E,associate's degree,standard,completed,95,100,100
148,female,group E,bachelor's degree,standard,completed,100,100,100
967,female,group E,master's degree,free/reduced,none,84,100,99
970,female,group D,some high school,standard,completed,85,100,97

In [35]:
df.sort_values("math score", ascending = False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
44,male,group E,high school,standard,none,100,88,87
550,female,group E,some college,standard,completed,100,100,100
235,male,group C,associate's degree,standard,completed,100,91,90
584,male,group C,bachelor's degree,standard,none,100,84,88
638,male,group E,high school,standard,none,100,82,80
...,...,...,...,...,...,...,...,...
908,female,group C,some college,free/reduced,completed,26,44,46
729,female,group B,some high school,free/reduced,none,25,36,37
18,female,group C,associate's degree,free/reduced,none,23,44,44
832,female,group D,some college,free/reduced,none,13,36,37
392,female,group C,some college,free/reduced,none,13,29,23

In [36]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [37]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [2]:
df.dropna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group A,high school,standard,completed,67,67,63
1,female,group D,some high school,free/reduced,none,40,59,55
2,male,group E,some college,free/reduced,none,59,60,50
3,male,group B,high school,standard,none,77,78,68
4,male,group E,associate's degree,standard,completed,78,73,68
...,...,...,...,...,...,...,...,...
995,male,group C,high school,standard,none,73,70,65
996,male,group D,associate's degree,free/reduced,completed,85,91,92
997,female,group C,some high school,free/reduced,none,32,35,41
998,female,group C,some college,standard,none,73,74,82
999,male,group A,some college,standard,completed,65,60,62

In [3]:
df=df.dropna()
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [3]:
df.shape   #There is no null values in this dataset

(1000, 8)