PANDAS USING DOWNLOADED DATASET FROM KAGGLE

Dataset has been downloaded from kaggle, and it will be present inside download in jupyter notebook. we have to use it here.
read_csv is a function that is present inside pandas to read the entire dataframe.

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\travel.csv")
print(df)

      CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0         200000          1  41.0     Self Enquiry         3              6.0
1         200001          0  49.0  Company Invited         1             14.0
2         200002          1  37.0     Self Enquiry         1              8.0
3         200003          0  33.0  Company Invited         1              9.0
4         200004          0   NaN     Self Enquiry         1              8.0
...          ...        ...   ...              ...       ...              ...
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0           Salaried  Female                       3                3.0
1           Salaried    Male                       3                4.0
2        Free Lancer    Male                       3                4.0
3           Salaried  Female                       2                3.0
4     Small Business    Male                       2                3.0
...              ...     ...                     ...                ...
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0            Deluxe                    3.0        Single            1.0
1            Deluxe                    4.0      Divorced            2.0
2             Basic                    3.0        Single            7.0
3             Basic                    3.0      Divorced            2.0
4             Basic                    4.0      Divorced            1.0
...             ...                    ...           ...            ...
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0            1                       2       1                       0.0
1            0                       3       1                       2.0
2            1                       3       0                       0.0
3            1                       5       1                       1.0
4            0                       5       1                       0.0
...        ...                     ...     ...                       ...
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
0            Manager        20993.0
1            Manager        20130.0
2          Executive        17090.0
3          Executive        17909.0
4          Executive        18468.0
...              ...            ...
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

[4888 rows x 20 columns]

Performing EDA on the dataset that has been downloaded

In [7]:
#head
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.head())  #it prints the datas
df.head()   #gives in table format itself with rows and cols

   CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0
1      200001          0  49.0  Company Invited         1             14.0
2      200002          1  37.0     Self Enquiry         1              8.0
3      200003          0  33.0  Company Invited         1              9.0
4      200004          0   NaN     Self Enquiry         1              8.0

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0
1        Salaried    Male                       3                4.0
2     Free Lancer    Male                       3                4.0
3        Salaried  Female                       2                3.0
4  Small Business    Male                       2                3.0

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0
1         Deluxe                    4.0      Divorced            2.0
2          Basic                    3.0        Single            7.0
3          Basic                    3.0      Divorced            2.0
4          Basic                    4.0      Divorced            1.0

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0
1         0                       3       1                       2.0
2         1                       3       0                       0.0
3         1                       5       1                       1.0
4         0                       5       1                       0.0

  Designation  MonthlyIncome
0     Manager        20993.0
1     Manager        20130.0
2   Executive        17090.0
3   Executive        17909.0
4   Executive        18468.0

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [8]:
#tail()
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.tail())  #it prints the datas
df.tail()

      CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [14]:
#info()
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\travel.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB
None

In [2]:
#describe()    -- analyses only the numerical columns
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\travel.csv")
df.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [3]:
#Shape
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\travel.csv")
print(df.shape)

(4888, 20)

In [2]:
#dtypes
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\travel.csv")
print(df.dtypes)

CustomerID                    int64
ProdTaken                     int64
Age                         float64
TypeofContact                object
CityTier                      int64
DurationOfPitch             float64
Occupation                   object
Gender                       object
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
ProductPitched               object
PreferredPropertyStar       float64
MaritalStatus                object
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
Designation                  object
MonthlyIncome               float64
dtype: object

Everytime we dont need all the columns, the columns which we need are only enough toanalyze. foe, eg if we have analyze the age column it is alone enough. we can get it in pandas alone

In [16]:
import pandas as pd
print(df['Age']) #name of the column

0       41.0
1       49.0
2       37.0
3       33.0
4        NaN
        ...
4883    49.0
4884    28.0
4885    52.0
4886    19.0
4887    36.0
Name: Age, Length: 4888, dtype: float64

In [17]:
#similarly if we need 2 or more columns
print(df[['Age','CityTier']])

       Age  CityTier
0     41.0         3
1     49.0         1
2     37.0         1
3     33.0         1
4      NaN         1
...    ...       ...
4883  49.0         3
4884  28.0         1
4885  52.0         3
4886  19.0         3
4887  36.0         1

[4888 rows x 2 columns]

In the above cells we could see all the rows till the end of the dataframe is getting printed. so we can specify the rows that we need also by using the method called as loc. By using loc both indexing and slicing can be done

LOC and ILOC

In [11]:
#loc is an instance vaiable which denotes the location
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\travel.csv")
print(df.loc[0])   # Similar to indexing in python

CustomerID                        200000
ProdTaken                              1
Age                                 41.0
TypeofContact               Self Enquiry
CityTier                               3
DurationOfPitch                      6.0
Occupation                      Salaried
Gender                            Female
NumberOfPersonVisiting                 3
NumberOfFollowups                    3.0
ProductPitched                    Deluxe
PreferredPropertyStar                3.0
MaritalStatus                     Single
NumberOfTrips                        1.0
Passport                               1
PitchSatisfactionScore                 2
OwnCar                                 1
NumberOfChildrenVisiting             0.0
Designation                      Manager
MonthlyIncome                    20993.0
Name: 0, dtype: object

In [2]:
#This is similar to slicing in python by using loc
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.loc[0:2])  #Prints the first 3rows

   CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0
1      200001          0  49.0  Company Invited         1             14.0
2      200002          1  37.0     Self Enquiry         1              8.0

    Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0     Salaried  Female                       3                3.0
1     Salaried    Male                       3                4.0
2  Free Lancer    Male                       3                4.0

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0
1         Deluxe                    4.0      Divorced            2.0
2          Basic                    3.0        Single            7.0

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0
1         0                       3       1                       2.0
2         1                       3       0                       0.0

  Designation  MonthlyIncome
0     Manager        20993.0
1     Manager        20130.0
2   Executive        17090.0

In [5]:
df.loc[0]

CustomerID                        200000
ProdTaken                              1
Age                                 41.0
TypeofContact               Self Enquiry
CityTier                               3
DurationOfPitch                      6.0
Occupation                      Salaried
Gender                            Female
NumberOfPersonVisiting                 3
NumberOfFollowups                    3.0
ProductPitched                    Deluxe
PreferredPropertyStar                3.0
MaritalStatus                     Single
NumberOfTrips                        1.0
Passport                               1
PitchSatisfactionScore                 2
OwnCar                                 1
NumberOfChildrenVisiting             0.0
Designation                      Manager
MonthlyIncome                    20993.0
Name: 0, dtype: object

In [6]:
df.iloc[0]

CustomerID                        200000
ProdTaken                              1
Age                                 41.0
TypeofContact               Self Enquiry
CityTier                               3
DurationOfPitch                      6.0
Occupation                      Salaried
Gender                            Female
NumberOfPersonVisiting                 3
NumberOfFollowups                    3.0
ProductPitched                    Deluxe
PreferredPropertyStar                3.0
MaritalStatus                     Single
NumberOfTrips                        1.0
Passport                               1
PitchSatisfactionScore                 2
OwnCar                                 1
NumberOfChildrenVisiting             0.0
Designation                      Manager
MonthlyIncome                    20993.0
Name: 0, dtype: object

In the both above cells, we could see loc[0] and iloc[0] gives the same output of only the 0th index that is 1st row.

In [7]:
df.loc[0:2]  #here in slicing in loc 0,1,2 (3 rows) will be printed where 2 is also included

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0

In [8]:
df.iloc[0:2]  #here in slicing in iloc only 0,1 (2 rows) will be printed where 2 is excluded here

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0

CONDITIONAL FILTERING OR BOOLEAN FILTERING

In [10]:
#Age of people which is greater than 40 
df[df["Age"]>40]   #To get the entire dataframe we should give it inside [] brackets

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
6,200006,0,59.0,Self Enquiry,1,9.0,Small Business,Female,2,2.0,Basic,5.0,Divorced,5.0,1,2,1,1.0,Executive,17670.0
18,200018,0,53.0,Self Enquiry,3,8.0,Salaried,Female,3,4.0,Super Deluxe,3.0,Divorced,3.0,0,3,1,0.0,AVP,30427.0
25,200025,0,53.0,Self Enquiry,1,11.0,Salaried,Female,2,3.0,King,3.0,Married,5.0,0,5,0,1.0,VP,34094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,204876,1,52.0,Self Enquiry,3,34.0,Salaried,Male,3,4.0,Deluxe,3.0,Single,3.0,1,5,1,2.0,Manager,32704.0
4880,204880,1,59.0,Self Enquiry,1,28.0,Small Business,Female,4,4.0,Deluxe,4.0,Married,6.0,0,3,1,2.0,Manager,28686.0
4881,204881,1,41.0,Self Enquiry,2,25.0,Salaried,Male,3,2.0,Basic,5.0,Married,2.0,0,1,1,2.0,Executive,21065.0
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0

In [9]:
df["Age"]>40   #If we do not give it inside the [] brackets, we will only get whether it is true or false and not the entire dataframe

0        True
1        True
2       False
3       False
4       False
        ...
4883     True
4884    False
4885     True
4886    False
4887    False
Name: Age, Length: 4888, dtype: bool

In [12]:
#Filtering using 2 conditions - Age and CityTier
df[(df["Age"]<35) & (df["CityTier"]==1)]

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0
7,200007,0,30.0,Self Enquiry,1,30.0,Salaried,Male,3,3.0,Basic,3.0,Married,2.0,0,2,0,1.0,Executive,17693.0
12,200012,0,31.0,Self Enquiry,1,32.0,Salaried,Male,2,3.0,Basic,3.0,Married,2.0,0,3,0,1.0,Executive,17911.0
13,200013,0,34.0,Self Enquiry,1,25.0,Small Business,Male,3,3.0,Basic,3.0,Married,1.0,0,3,0,2.0,Executive,17661.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4849,204849,1,33.0,Company Invited,1,10.0,Salaried,Fe Male,3,4.0,Basic,3.0,Unmarried,3.0,0,4,1,1.0,Executive,24887.0
4853,204853,1,33.0,Self Enquiry,1,9.0,Small Business,Male,3,4.0,Deluxe,4.0,Married,6.0,0,4,1,2.0,Manager,23561.0
4858,204858,1,29.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,5.0,Unmarried,5.0,1,3,0,3.0,Executive,25352.0
4862,204862,1,31.0,Self Enquiry,1,9.0,Salaried,Male,4,4.0,Basic,4.0,Single,3.0,0,3,0,1.0,Executive,30594.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0

In [19]:
#Filtering using age,gender and occupation at same time
df[(df["Age"]>=25) & (df["Age"]<=40) & (df["Gender"]=="Male") & (df["Occupation"]=="Salaried")]

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0
7,200007,0,30.0,Self Enquiry,1,30.0,Salaried,Male,3,3.0,Basic,3.0,Married,2.0,0,2,0,1.0,Executive,17693.0
8,200008,0,38.0,Company Invited,1,29.0,Salaried,Male,2,4.0,Standard,3.0,Unmarried,1.0,0,3,0,0.0,Senior Manager,24526.0
12,200012,0,31.0,Self Enquiry,1,32.0,Salaried,Male,2,3.0,Basic,3.0,Married,2.0,0,3,0,1.0,Executive,17911.0
14,200014,1,28.0,Self Enquiry,1,30.0,Salaried,Male,2,4.0,Basic,3.0,Single,6.0,1,2,0,0.0,Executive,17028.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4864,204864,1,32.0,Self Enquiry,2,29.0,Salaried,Male,3,6.0,Basic,3.0,Married,3.0,0,1,0,2.0,Executive,28530.0
4877,204877,1,39.0,Company Invited,1,16.0,Salaried,Male,4,4.0,Deluxe,5.0,Married,6.0,0,3,0,3.0,Manager,25571.0
4882,204882,1,37.0,Self Enquiry,2,20.0,Salaried,Male,3,5.0,Basic,5.0,Married,6.0,1,5,1,2.0,Executive,23317.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

SORTING OF DATAS
The raw datas will not be arranged in any order properly. So we need to sort it either in asc or desc order
asc --> Lower - Higher
desc--> Higher - Lower

Sort_values(by) is a method in the dataframe that holds a default parameter called as 'by' where we should give the column name by which it should be sorted.

In [12]:
df.sort_values(by="Age")
#or
df.sort_values("Age")   #This gives the output of age that is sorted in ascending order by default.

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
828,200828,1,18.0,Company Invited,1,14.0,Small Business,Male,3,3.0,Basic,3.0,Single,2.0,0,5,0,0.0,Executive,16904.0
727,200727,0,18.0,Company Invited,1,11.0,Salaried,Male,3,3.0,Basic,3.0,Single,2.0,0,2,1,1.0,Executive,16051.0
2442,202442,1,18.0,Self Enquiry,3,15.0,Small Business,Male,2,3.0,Basic,3.0,Single,2.0,0,5,0,1.0,Executive,16611.0
972,200972,0,18.0,Company Invited,1,6.0,Salaried,Female,3,3.0,Basic,3.0,Single,2.0,0,5,1,1.0,Executive,16611.0
2298,202298,1,18.0,Company Invited,1,14.0,Small Business,Male,3,3.0,Basic,3.0,Single,2.0,0,5,1,0.0,Executive,16904.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,202410,1,NaN,Self Enquiry,1,30.0,Small Business,Male,2,3.0,Basic,4.0,Married,2.0,1,1,0,0.0,Executive,NaN
2413,202413,1,NaN,Self Enquiry,3,21.0,Small Business,Male,2,5.0,Deluxe,3.0,Married,7.0,1,1,0,1.0,Manager,18423.0
2427,202427,1,NaN,Self Enquiry,3,22.0,Small Business,Male,3,3.0,Standard,3.0,Married,3.0,0,5,0,1.0,Senior Manager,18544.0
2430,202430,1,NaN,Self Enquiry,1,14.0,Small Business,Female,3,3.0,Basic,5.0,Married,2.0,1,3,0,2.0,Executive,NaN
2435,202435,1,NaN,Self Enquiry,2,26.0,Small Business,Female,3,3.0,Basic,4.0,Married,1.0,1,3,0,1.0,Executive,18669.0

In [21]:
#def sort_values(by, ascending=True) --> default parameter=True 
df.sort_values("Age", ascending=False)  _#Here we gave false, and hence the age will be sorted in desc order.

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
3653,203653,0,61.0,Self Enquiry,1,7.0,Small Business,Male,4,6.0,Standard,3.0,Married,5.0,0,5,0,1.0,Senior Manager,29561.0
4793,204793,0,61.0,Self Enquiry,3,14.0,Small Business,Male,3,2.0,Deluxe,3.0,Married,2.0,1,5,0,1.0,Manager,23898.0
2855,202855,0,61.0,Self Enquiry,1,14.0,Salaried,Female,3,4.0,King,5.0,Divorced,7.0,0,5,0,1.0,VP,38244.0
2871,202871,0,61.0,Company Invited,3,35.0,Small Business,Female,4,5.0,Standard,5.0,Divorced,6.0,0,2,1,1.0,Senior Manager,28944.0
3323,203323,0,61.0,Self Enquiry,3,14.0,Small Business,Male,3,2.0,Deluxe,3.0,Married,2.0,1,5,0,1.0,Manager,23898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,202410,1,NaN,Self Enquiry,1,30.0,Small Business,Male,2,3.0,Basic,4.0,Married,2.0,1,1,0,0.0,Executive,NaN
2413,202413,1,NaN,Self Enquiry,3,21.0,Small Business,Male,2,5.0,Deluxe,3.0,Married,7.0,1,1,0,1.0,Manager,18423.0
2427,202427,1,NaN,Self Enquiry,3,22.0,Small Business,Male,3,3.0,Standard,3.0,Married,3.0,0,5,0,1.0,Senior Manager,18544.0
2430,202430,1,NaN,Self Enquiry,1,14.0,Small Business,Female,3,3.0,Basic,5.0,Married,2.0,1,3,0,2.0,Executive,NaN
2435,202435,1,NaN,Self Enquiry,2,26.0,Small Business,Female,3,3.0,Basic,4.0,Married,1.0,1,3,0,1.0,Executive,18669.0

MISSING VALUES
We cannot ignore missing datas and analyze the dataset as it is. If we do so, the conclusion will not be correct. So handling the missing values is very important.

In [15]:
#First we have to check whether there is any missing values present in the dataset, by using isnull() which is a method.
df.isnull()  #Gives True or False (If True-->missing value, False-->Data is present)

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4884,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4885,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4886,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
df.isnull().sum()  #sum() Gives the count of missing values for each columns completely.

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

Different ways of handling missing values in pandas
1. dropna()
2. fillna()

DROPNA() - It is a method present inside the dataframe 
If the rows contain any null values the entire row will be dropped in the dataframe.
drops all the rows containg null values in it.
When dropna() is used, it creates a copy of the original dataframe and the rows will be dropped in the copy, keeping the original dataframe safe.

In [11]:
df.dropna()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [6]:
df=df.dropna()
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [14]:
#Initially there was 4888 rows in the table, and now we can check how many rows are there after dropping roews with null values
print(df.shape)  #Only 4128 are present after dropping rows with null values.
#But if so many rows are removed like this, the conclusion we get after performing Data analysis would not be correct.

(4128, 20)

Till this, dropna() created a new data frame and made changes in that. If we need the changes to be done in the same dataframe (or) excel sheet,
INPLACE should be given as parameter and the default value False should be changed to True

In [8]:
df.dropna(inplace=True)   #This makes changes in the original dataframe itself.
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [10]:
df.shape

(4128, 20)

FILLNA()
Whereever there are missing values, we need to fill it with some datas, instead of dropping the rows entirely.
Then we should use Fillna() method. In fillna() also inplace works like same as dropna().
string columns cannot accept integer values 0 tobe filled. So we have to identify only interger columns and fill 0 there

In [3]:
df.fillna(0,inplace=True)
print(df)

      CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0         200000          1  41.0     Self Enquiry         3              6.0
1         200001          0  49.0  Company Invited         1             14.0
2         200002          1  37.0     Self Enquiry         1              8.0
3         200003          0  33.0  Company Invited         1              9.0
4         200004          0   0.0     Self Enquiry         1              8.0
...          ...        ...   ...              ...       ...              ...
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0           Salaried  Female                       3                3.0
1           Salaried    Male                       3                4.0
2        Free Lancer    Male                       3                4.0
3           Salaried  Female                       2                3.0
4     Small Business    Male                       2                3.0
...              ...     ...                     ...                ...
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0            Deluxe                    3.0        Single            1.0
1            Deluxe                    4.0      Divorced            2.0
2             Basic                    3.0        Single            7.0
3             Basic                    3.0      Divorced            2.0
4             Basic                    4.0      Divorced            1.0
...             ...                    ...           ...            ...
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0            1                       2       1                       0.0
1            0                       3       1                       2.0
2            1                       3       0                       0.0
3            1                       5       1                       1.0
4            0                       5       1                       0.0
...        ...                     ...     ...                       ...
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
0            Manager        20993.0
1            Manager        20130.0
2          Executive        17090.0
3          Executive        17909.0
4          Executive        18468.0
...              ...            ...
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

[4888 rows x 20 columns]

In [9]:
#FILLNA()

num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_columns].fillna(0)
print(df)

      CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0         200000          1  41.0     Self Enquiry         3              6.0
1         200001          0  49.0  Company Invited         1             14.0
2         200002          1  37.0     Self Enquiry         1              8.0
3         200003          0  33.0  Company Invited         1              9.0
4         200004          0   0.0     Self Enquiry         1              8.0
...          ...        ...   ...              ...       ...              ...
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0           Salaried  Female                       3                3.0
1           Salaried    Male                       3                4.0
2        Free Lancer    Male                       3                4.0
3           Salaried  Female                       2                3.0
4     Small Business    Male                       2                3.0
...              ...     ...                     ...                ...
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0            Deluxe                    3.0        Single            1.0
1            Deluxe                    4.0      Divorced            2.0
2             Basic                    3.0        Single            7.0
3             Basic                    3.0      Divorced            2.0
4             Basic                    4.0      Divorced            1.0
...             ...                    ...           ...            ...
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0            1                       2       1                       0.0
1            0                       3       1                       2.0
2            1                       3       0                       0.0
3            1                       5       1                       1.0
4            0                       5       1                       0.0
...        ...                     ...     ...                       ...
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
0            Manager        20993.0
1            Manager        20130.0
2          Executive        17090.0
3          Executive        17909.0
4          Executive        18468.0
...              ...            ...
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

[4888 rows x 20 columns]

In [34]:
cat_cols = df.select_dtypes(exclude='number').columns
df[cat_cols] = df[cat_cols].fillna('Unknown')
print(df)

      CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0         200000          1  41.0     Self Enquiry         3              6.0
1         200001          0  49.0  Company Invited         1             14.0
2         200002          1  37.0     Self Enquiry         1              8.0
3         200003          0  33.0  Company Invited         1              9.0
4         200004          0   NaN     Self Enquiry         1              8.0
...          ...        ...   ...              ...       ...              ...
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0           Salaried  Female                       3                3.0
1           Salaried    Male                       3                4.0
2        Free Lancer    Male                       3                4.0
3           Salaried  Female                       2                3.0
4     Small Business    Male                       2                3.0
...              ...     ...                     ...                ...
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0            Deluxe                    3.0        Single            1.0
1            Deluxe                    4.0      Divorced            2.0
2             Basic                    3.0        Single            7.0
3             Basic                    3.0      Divorced            2.0
4             Basic                    4.0      Divorced            1.0
...             ...                    ...           ...            ...
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0            1                       2       1                       0.0
1            0                       3       1                       2.0
2            1                       3       0                       0.0
3            1                       5       1                       1.0
4            0                       5       1                       0.0
...        ...                     ...     ...                       ...
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
0            Manager        20993.0
1            Manager        20130.0
2          Executive        17090.0
3          Executive        17909.0
4          Executive        18468.0
...              ...            ...
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

[4888 rows x 20 columns]

In [35]:
df.iloc[250:356:2]

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
250,200250,1,37.0,Company Invited,1,16.0,Small Business,Male,3,3.0,Standard,3.0,Married,7.0,0,3,1,2.0,Senior Manager,25048.0
252,200252,0,29.0,Self Enquiry,1,21.0,Salaried,Male,2,3.0,Basic,3.0,Single,2.0,0,3,0,0.0,Executive,17340.0
254,200254,0,29.0,Self Enquiry,3,26.0,Small Business,Male,2,3.0,Deluxe,3.0,Married,3.0,0,2,1,1.0,Manager,21931.0
256,200256,0,42.0,Self Enquiry,1,8.0,Small Business,Female,2,4.0,Basic,5.0,Married,1.0,1,4,1,0.0,Executive,17593.0
258,200258,0,51.0,Self Enquiry,1,6.0,Salaried,Male,3,3.0,Basic,3.0,Divorced,2.0,0,4,1,0.0,Executive,17723.0
260,200260,0,32.0,Company Invited,1,13.0,Salaried,Male,3,2.0,Basic,4.0,Divorced,2.0,0,2,0,1.0,Executive,17794.0
262,200262,0,32.0,Self Enquiry,1,8.0,Large Business,Male,2,4.0,Deluxe,5.0,Single,5.0,0,4,0,1.0,Manager,17176.0
264,200264,1,NaN,Self Enquiry,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,3.0,0,4,1,1.0,Executive,18485.0
266,200266,0,31.0,Self Enquiry,1,29.0,Small Business,Male,3,4.0,Deluxe,3.0,Divorced,1.0,0,3,1,1.0,Manager,20582.0
268,200268,0,45.0,Self Enquiry,1,26.0,Small Business,Male,3,3.0,Super Deluxe,3.0,Divorced,1.0,1,3,0,0.0,AVP,28496.0
270,200270,0,55.0,Self Enquiry,1,6.0,Small Business,Male,2,3.0,King,5.0,Single,1.0,1,2,1,0.0,VP,34045.0
272,200272,0,28.0,Self Enquiry,1,15.0,Small Business,Male,3,3.0,Basic,3.0,Divorced,2.0,0,2,1,1.0,Executive,17070.0
274,200274,0,21.0,Self Enquiry,1,9.0,Small Business,Male,3,4.0,Basic,3.0,Single,2.0,0,5,1,1.0,Executive,18230.0
276,200276,0,35.0,Self Enquiry,1,28.0,Salaried,Female,3,2.0,Standard,4.0,Married,1.0,0,5,1,1.0,Senior Manager,26996.0
278,200278,0,26.0,Company Invited,1,6.0,Salaried,Female,2,3.0,Deluxe,4.0,Married,2.0,0,5,0,1.0,Manager,21397.0
280,200280,0,53.0,Self Enquiry,1,9.0,Small Business,Male,2,3.0,Super Deluxe,3.0,Divorced,4.0,1,5,0,0.0,AVP,32584.0
282,200282,0,29.0,Company Invited,3,NaN,Salaried,Male,2,3.0,Deluxe,3.0,Single,2.0,0,2,0,0.0,Manager,19554.0
284,200284,0,26.0,Company Invited,1,NaN,Small Business,Male,2,3.0,Deluxe,5.0,Divorced,2.0,1,3,1,1.0,Manager,19741.0
286,200286,1,44.0,Company Invited,1,30.0,Salaried,Male,2,3.0,Basic,3.0,Married,4.0,1,5,0,1.0,Executive,18161.0
288,200288,1,26.0,Self Enquiry,1,22.0,Small Business,Male,2,3.0,Basic,4.0,Married,3.0,1,2,1,1.0,Executive,17373.0
290,200290,0,49.0,Company Invited,1,16.0,Salaried,Female,2,3.0,King,5.0,Single,1.0,1,3,0,0.0,VP,33665.0
292,200292,0,31.0,Company Invited,3,11.0,Small Business,Female,2,3.0,Basic,4.0,Married,2.0,0,3,0,1.0,Executive,17789.0
294,200294,0,37.0,Company Invited,1,15.0,Small Business,Male,2,3.0,Basic,3.0,Divorced,2.0,1,2,0,0.0,Executive,17326.0
296,200296,1,18.0,Self Enquiry,1,9.0,Salaried,Male,2,3.0,Basic,3.0,Single,2.0,0,4,0,0.0,Executive,16420.0
298,200298,0,NaN,Company Invited,1,24.0,Salaried,Male,2,2.0,Basic,3.0,Divorced,5.0,0,5,0,0.0,Executive,18688.0
300,200300,0,41.0,Self Enquiry,3,8.0,Salaried,Male,2,3.0,Super Deluxe,4.0,Single,2.0,0,3,1,0.0,AVP,31015.0
302,200302,0,28.0,Self Enquiry,1,22.0,Small Business,Male,3,2.0,Deluxe,5.0,Single,1.0,0,5,0,2.0,Manager,20661.0
304,200304,0,39.0,Self Enquiry,1,6.0,Small Business,Male,2,2.0,Standard,3.0,Married,1.0,0,3,1,0.0,Senior Manager,24613.0
306,200306,0,32.0,Self Enquiry,3,13.0,Salaried,Male,3,4.0,Deluxe,3.0,Divorced,2.0,0,3,1,2.0,Manager,20484.0
308,200308,0,58.0,Company Invited,1,6.0,Salaried,Male,2,5.0,Deluxe,3.0,Married,3.0,1,2,1,1.0,Manager,20660.0
310,200310,0,31.0,Self Enquiry,2,8.0,Salaried,Male,3,4.0,Deluxe,5.0,Divorced,4.0,0,3,0,1.0,Manager,21410.0
312,200312,0,31.0,Self Enquiry,1,8.0,Salaried,Male,2,3.0,Basic,3.0,Married,1.0,1,4,1,1.0,Executive,17695.0
314,200314,0,39.0,Self Enquiry,1,16.0,Small Business,Male,2,3.0,Super Deluxe,5.0,Divorced,2.0,1,3,1,1.0,AVP,32068.0
316,200316,0,49.0,Self Enquiry,1,6.0,Large Business,Female,2,4.0,Super Deluxe,3.0,Single,1.0,1,3,1,0.0,AVP,28964.0
318,200318,0,27.0,Self Enquiry,1,11.0,Salaried,Female,2,3.0,Basic,4.0,Single,2.0,1,3,0,1.0,Executive,17478.0
320,200320,0,27.0,Self Enquiry,3,NaN,Salaried,Male,3,3.0,Deluxe,3.0,Single,2.0,1,4,1,2.0,Manager,NaN
322,200322,0,32.0,Self Enquiry,1,8.0,Small Business,Female,3,NaN,Deluxe,3.0,Single,1.0,0,3,1,2.0,Manager,20055.0
324,200324,0,30.0,Self Enquiry,1,34.0,Small Business,Female,3,3.0,Deluxe,3.0,Divorced,2.0,0,3,0,2.0,Manager,20775.0
326,200326,0,39.0,Company Invited,1,5.0,Small Business,Male,2,4.0,King,3.0,Divorced,2.0,0,5,1,1.0,VP,34272.0
328,200328,0,33.0,Company Invited,3,NaN,Small Business,Male,2,4.0,Deluxe,3.0,Single,4.0,0,3,1,1.0,Manager,19682.0
330,200330,0,43.0,Company Invited,1,16.0,Salaried,Female,2,4.0,Deluxe,3.0,Married,2.0,0,3,0,0.0,Manager,20257.0
332,200332,0,54.0,Company Invited,1,NaN,Salaried,Female,2,3.0,Deluxe,3.0,Single,4.0,0,4,1,0.0,Manager,19869.0
334,200334,0,NaN,Self Enquiry,1,14.0,Salaried,Male,3,3.0,Deluxe,3.0,Divorced,1.0,0,3,1,0.0,Manager,18697.0
336,200336,1,29.0,Self Enquiry,1,14.0,Salaried,Male,3,5.0,Basic,5.0,Divorced,2.0,1,3,1,1.0,Executive,17119.0
338,200338,0,30.0,Self Enquiry,3,11.0,Small Business,Female,1,4.0,Deluxe,3.0,Married,2.0,0,2,0,0.0,Manager,21118.0
340,200340,0,37.0,Self Enquiry,1,11.0,Small Business,Male,3,3.0,Deluxe,3.0,Married,1.0,0,3,0,0.0,Manager,21347.0
342,200342,0,31.0,Self Enquiry,1,13.0,Small Business,Female,2,3.0,Standard,3.0,Unmarried,2.0,1,4,1,1.0,Senior Manager,22143.0
344,200344,0,35.0,Self Enquiry,1,11.0,Large Business,Male,3,3.0,Standard,4.0,Unmarried,1.0,0,3,0,0.0,Senior Manager,23095.0
346,200346,0,41.0,Self Enquiry,1,12.0,Small Business,Male,3,4.0,Deluxe,4.0,Single,7.0,1,3,1,0.0,Manager,21032.0
348,200348,0,42.0,Self Enquiry,1,29.0,Salaried,Female,2,3.0,Super Deluxe,3.0,Single,3.0,0,3,0,0.0,AVP,30992.0
350,200350,0,42.0,Self Enquiry,2,8.0,Large Business,Male,2,3.0,Basic,3.0,Married,1.0,1,4,1,0.0,Executive,17696.0
352,200352,0,48.0,Self Enquiry,3,35.0,Small Business,Female,3,3.0,Standard,3.0,Divorced,4.0,0,4,0,0.0,Senior Manager,27504.0
354,200354,0,30.0,Company Invited,3,NaN,Large Business,Female,2,3.0,Deluxe,3.0,Divorced,1.0,1,3,1,0.0,Manager,19736.0

Handling duplicate values in pandas
1. Find if there is duplicate rows in the dataset  -- duplicated()
2.drop the duplicate rows in the dataset -- drop_duplicates()

In [12]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\travel.csv")
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4883    False
4884    False
4885    False
4886    False
4887    False
Length: 4888, dtype: bool

In [13]:
df.drop_duplicates()  #Drops the duplicate rows

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [2]:
import pandas as pd
data={
    'Name':["Tim","Raj","Rishi","Nithish","Tim","Raj","Rishi","Nithish"],  #Multiple datas given inside list and every feature of list can be accessed here like duplicate values,heterogenous datas,etc
    'Age':[25,49,21,25,25,49,21,25]
}
df=pd.DataFrame(data) #In pandas we should not tell as table, it is called "DataFrame".
print(df)

      Name  Age
0      Tim   25
1      Raj   49
2    Rishi   21
3  Nithish   25
4      Tim   25
5      Raj   49
6    Rishi   21
7  Nithish   25

In [3]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
dtype: bool

In [4]:
df.drop_duplicates()

      Name  Age
0      Tim   25
1      Raj   49
2    Rishi   21
3  Nithish   25

Converting the string age into integer Age

In [20]:
import pandas
data={
    'Name':["Tim","Raj","Rishi","Nithish"],  #Multiple datas given inside list and every fature of list can be accessed here like duplicate values,heterogenous datas,etc
    'Age':["Ten","Nine","Eight","Seven"]
}
df=pandas.DataFrame(data) #In pandas we should not tell as table, it is called "DataFrame".
df["Age"]=df["Age"].astype("int")
#This give error, because it cannot process the strings like "Ten", "Nine" so it should be in base 10 "10","9"

ValueError: invalid literal for int() with base 10: 'Ten'

In [40]:
import pandas
data={
    'Name':["Tim","Raj","Rishi","Nithish"],  
    'Age':["25","49","21","25"]  #here the ages are in strings, so now astype("int") will convert it as integer
}
df=pandas.DataFrame(data)
print(df)

      Name Age
0      Tim  25
1      Raj  49
2    Rishi  21
3  Nithish  25

In [41]:
df["Age"]=df["Age"].astype('int')
print(df)

      Name  Age
0      Tim   25
1      Raj   49
2    Rishi   21
3  Nithish   25

Adding a new column in the dataset
We have to add the maths and science and create a new  columns as Total
It first whether any total column exist in the dataframe, it it exits with 0 as value then it adds the maths and science marks and stores in it.
if there is no columns as total, then it adds a new column in the dataframe

In [46]:
import pandas
data={
    'Name':["Tim","Raj","Rishi","Nithish"],  #Multiple datas given inside list and every fature of list can be accessed here like duplicate values,heterogenous datas,etc
    'Maths':[100,99,100,98],
    'Science':[100,89,97,93]
}
df=pd.DataFrame(data)
df['Total']=df['Maths'] + df['Science']  #A new column Total have been added in the dataframe
df

      Name  Maths  Science  Total
0      Tim    100      100    200
1      Raj     99       89    188
2    Rishi    100       97    197
3  Nithish     98       93    191

Concatenation of two dataframes - Vertically attached
In the below example, we have to get the total sales of both july and aug month which are in two separate dataframes.
This concat() attaches two datasets in a new dataframe.
Here we have combined 2 dataframes vertically, one below the other

In [47]:
import pandas
Julydata={
    'Products':["iphone","ipad","Mac","Tablet"],  
    'Total':[100,99,100,98]
}
Julysales=pd.DataFrame(Julydata)

import pandas
Augdata={
    'Products':["iphone","ipad","Mac","Tablet"],  
    'Total':[250,199,46,68]
}
Augsales=pd.DataFrame(Augdata)

result=pd.concat([Julysales,Augsales])
result

  Products  Total
0   iphone    100
1     ipad     99
2      Mac    100
3   Tablet     98
0   iphone    250
1     ipad    199
2      Mac     46
3   Tablet     68

Merging of datasets - Horizontally Attached

In [9]:
import pandas as pd
data1={
    "Id" : [1,2,3,4],
    "Name" : ["Raj", "Rishi", "Khamal", "Eniyan"]
}
df1=pd.DataFrame(data1)

data2={
    "Id" : [1,2,3,4],
    "Grade" : ["A", "C", "B", "A"]
}
df2=pd.DataFrame(data2)

result=pd.merge(df1,df2, on = 'Id')
result

   Id    Name Grade
0   1     Raj     A
1   2   Rishi     C
2   3  Khamal     B
3   4  Eniyan     A

Aggregate functions on Pandas - Aggregation should be performed only on numerical columns.
1. count()
2. sum()
3. mean()

In [23]:
data={
    "Subject" : ["Maths","Science","Social", "English","Tamil"],
    "Marks" :[100,100,99,56,78]
}
raju=pd.DataFrame(data)

In [24]:
#Count()
count=raju["Marks"].count()
count

#or

m=raju["Marks"]
c=m.count()
print(c)

#or
raju["Marks"].count()

5

np.int64(5)

In [29]:
#Sum()
sum=raju["Marks"].sum()
sum

#or

m=raju["Marks"]
s=m.sum()
print(s)

raju["Marks"].sum()

433

np.int64(433)

In [32]:
#Mean()
mean=raju["Marks"].mean()
mean

#or

m=raju["Marks"]
mean=m.mean()
print(mean)

raju["Marks"].mean()

86.6

np.float64(86.6)

In [42]:
data1={
    "Id" : [1,2,3,4],
    "Name" : ["raj", "  Rishi", "khamal   ", " eniyan"]
}
df1=pd.DataFrame(data1)
df1

   Id       Name
0   1        raj
1   2      Rishi
2   3  khamal
3   4     eniyan

In [41]:
df1["Name"]=df1["Name"].str.strip()
df1

   Id    Name
0   1     Raj
1   2   Rishi
2   3  Khamal
3   4  Eniyan

In [40]:
df1["Name"]=df1["Name"].str.capitalize()
df1

   Id    Name
0   1     Raj
1   2   Rishi
2   3  Khamal
3   4  Eniyan