PANDAS USING DOWNLOADED DATASET FROM KAGGLE

Dataset has been downloaded from kaggle, and it will be present inside download in jupyter notebook. we have to use it here.
read_csv is a function that is present inside pandas to read the entire dataframe.

In [3]:
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df)

      CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0         200000          1  41.0     Self Enquiry         3              6.0
1         200001          0  49.0  Company Invited         1             14.0
2         200002          1  37.0     Self Enquiry         1              8.0
3         200003          0  33.0  Company Invited         1              9.0
4         200004          0   NaN     Self Enquiry         1              8.0
...          ...        ...   ...              ...       ...              ...
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0           Salaried  Female                       3                3.0
1           Salaried    Male                       3                4.0
2        Free Lancer    Male                       3                4.0
3           Salaried  Female                       2                3.0
4     Small Business    Male                       2                3.0
...              ...     ...                     ...                ...
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0            Deluxe                    3.0        Single            1.0
1            Deluxe                    4.0      Divorced            2.0
2             Basic                    3.0        Single            7.0
3             Basic                    3.0      Divorced            2.0
4             Basic                    4.0      Divorced            1.0
...             ...                    ...           ...            ...
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0            1                       2       1                       0.0
1            0                       3       1                       2.0
2            1                       3       0                       0.0
3            1                       5       1                       1.0
4            0                       5       1                       0.0
...        ...                     ...     ...                       ...
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
0            Manager        20993.0
1            Manager        20130.0
2          Executive        17090.0
3          Executive        17909.0
4          Executive        18468.0
...              ...            ...
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

[4888 rows x 20 columns]

Performing EDA on the dataset that has been downloaded

In [7]:
#head
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.head())  #it prints the datas
df.head()   #gives in table format itself with rows and cols

   CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0
1      200001          0  49.0  Company Invited         1             14.0
2      200002          1  37.0     Self Enquiry         1              8.0
3      200003          0  33.0  Company Invited         1              9.0
4      200004          0   NaN     Self Enquiry         1              8.0

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0
1        Salaried    Male                       3                4.0
2     Free Lancer    Male                       3                4.0
3        Salaried  Female                       2                3.0
4  Small Business    Male                       2                3.0

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0
1         Deluxe                    4.0      Divorced            2.0
2          Basic                    3.0        Single            7.0
3          Basic                    3.0      Divorced            2.0
4          Basic                    4.0      Divorced            1.0

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0
1         0                       3       1                       2.0
2         1                       3       0                       0.0
3         1                       5       1                       1.0
4         0                       5       1                       0.0

  Designation  MonthlyIncome
0     Manager        20993.0
1     Manager        20130.0
2   Executive        17090.0
3   Executive        17909.0
4   Executive        18468.0

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [8]:
#tail()
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.tail())  #it prints the datas
df.tail()

      CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [10]:
#info()
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB
None

In [11]:
#describe()    -- analyses only the numerical columns
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.describe())

          CustomerID    ProdTaken          Age     CityTier  DurationOfPitch  \
count    4888.000000  4888.000000  4662.000000  4888.000000      4637.000000
mean   202443.500000     0.188216    37.622265     1.654255        15.490835
std      1411.188388     0.390925     9.316387     0.916583         8.519643
min    200000.000000     0.000000    18.000000     1.000000         5.000000
25%    201221.750000     0.000000    31.000000     1.000000         9.000000
50%    202443.500000     0.000000    36.000000     1.000000        13.000000
75%    203665.250000     0.000000    44.000000     3.000000        20.000000
max    204887.000000     1.000000    61.000000     3.000000       127.000000

       NumberOfPersonVisiting  NumberOfFollowups  PreferredPropertyStar  \
count             4888.000000        4843.000000            4862.000000
mean                 2.905074           3.708445               3.581037
std                  0.724891           1.002509               0.798009
min                  1.000000           1.000000               3.000000
25%                  2.000000           3.000000               3.000000
50%                  3.000000           4.000000               3.000000
75%                  3.000000           4.000000               4.000000
max                  5.000000           6.000000               5.000000

       NumberOfTrips     Passport  PitchSatisfactionScore       OwnCar  \
count    4748.000000  4888.000000             4888.000000  4888.000000
mean        3.236521     0.290917                3.078151     0.620295
std         1.849019     0.454232                1.365792     0.485363
min         1.000000     0.000000                1.000000     0.000000
25%         2.000000     0.000000                2.000000     0.000000
50%         3.000000     0.000000                3.000000     1.000000
75%         4.000000     1.000000                4.000000     1.000000
max        22.000000     1.000000                5.000000     1.000000

       NumberOfChildrenVisiting  MonthlyIncome
count               4822.000000    4655.000000
mean                   1.187267   23619.853491
std                    0.857861    5380.698361
min                    0.000000    1000.000000
25%                    1.000000   20346.000000
50%                    1.000000   22347.000000
75%                    2.000000   25571.000000
max                    3.000000   98678.000000

In [13]:
#Shape
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.shape)

(4888, 20)

In [14]:
#dtypes
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.dtypes)

CustomerID                    int64
ProdTaken                     int64
Age                         float64
TypeofContact                object
CityTier                      int64
DurationOfPitch             float64
Occupation                   object
Gender                       object
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
ProductPitched               object
PreferredPropertyStar       float64
MaritalStatus                object
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
Designation                  object
MonthlyIncome               float64
dtype: object

Everytime we dont need all the columns, the columns which we need are only enough toanalyze. foe, eg if we have analyze the age column it is alone enough. we can get it in pandas alone

In [16]:
import pandas as pd
print(df['Age']) #name of the column

0       41.0
1       49.0
2       37.0
3       33.0
4        NaN
        ...
4883    49.0
4884    28.0
4885    52.0
4886    19.0
4887    36.0
Name: Age, Length: 4888, dtype: float64

In [17]:
#similarly if we need 2 or more columns
print(df[['Age','CityTier']])

       Age  CityTier
0     41.0         3
1     49.0         1
2     37.0         1
3     33.0         1
4      NaN         1
...    ...       ...
4883  49.0         3
4884  28.0         1
4885  52.0         3
4886  19.0         3
4887  36.0         1

[4888 rows x 2 columns]

In the above cells we could see all the rows till the end of the dataframe is getting printed. so we can specify the rows that we need also by using the method called as loc. By using loc both indexing and slicing can be done

LOC and ILOC

In [19]:
#loc is an instance vaiable which denotes the location
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.loc[0])   # Similar to indexing in python

CustomerID                        200000
ProdTaken                              1
Age                                 41.0
TypeofContact               Self Enquiry
CityTier                               3
DurationOfPitch                      6.0
Occupation                      Salaried
Gender                            Female
NumberOfPersonVisiting                 3
NumberOfFollowups                    3.0
ProductPitched                    Deluxe
PreferredPropertyStar                3.0
MaritalStatus                     Single
NumberOfTrips                        1.0
Passport                               1
PitchSatisfactionScore                 2
OwnCar                                 1
NumberOfChildrenVisiting             0.0
Designation                      Manager
MonthlyIncome                    20993.0
Name: 0, dtype: object

In [2]:
#This is similar to slicing in python by using loc
import pandas as pd
df=pd.read_csv("Travel.csv")
print(df.loc[0:2])  #Prints the first 3rows

   CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0
1      200001          0  49.0  Company Invited         1             14.0
2      200002          1  37.0     Self Enquiry         1              8.0

    Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0     Salaried  Female                       3                3.0
1     Salaried    Male                       3                4.0
2  Free Lancer    Male                       3                4.0

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0
1         Deluxe                    4.0      Divorced            2.0
2          Basic                    3.0        Single            7.0

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0
1         0                       3       1                       2.0
2         1                       3       0                       0.0

  Designation  MonthlyIncome
0     Manager        20993.0
1     Manager        20130.0
2   Executive        17090.0

In [5]:
df.loc[0]

CustomerID                        200000
ProdTaken                              1
Age                                 41.0
TypeofContact               Self Enquiry
CityTier                               3
DurationOfPitch                      6.0
Occupation                      Salaried
Gender                            Female
NumberOfPersonVisiting                 3
NumberOfFollowups                    3.0
ProductPitched                    Deluxe
PreferredPropertyStar                3.0
MaritalStatus                     Single
NumberOfTrips                        1.0
Passport                               1
PitchSatisfactionScore                 2
OwnCar                                 1
NumberOfChildrenVisiting             0.0
Designation                      Manager
MonthlyIncome                    20993.0
Name: 0, dtype: object

In [6]:
df.iloc[0]

CustomerID                        200000
ProdTaken                              1
Age                                 41.0
TypeofContact               Self Enquiry
CityTier                               3
DurationOfPitch                      6.0
Occupation                      Salaried
Gender                            Female
NumberOfPersonVisiting                 3
NumberOfFollowups                    3.0
ProductPitched                    Deluxe
PreferredPropertyStar                3.0
MaritalStatus                     Single
NumberOfTrips                        1.0
Passport                               1
PitchSatisfactionScore                 2
OwnCar                                 1
NumberOfChildrenVisiting             0.0
Designation                      Manager
MonthlyIncome                    20993.0
Name: 0, dtype: object

In the both above cells, we could see loc[0] and iloc[0] gives the same output of only the 0th index that is 1st row.

In [7]:
df.loc[0:2]  #here in slicing in loc 0,1,2 (3 rows) will be printed where 2 is also included

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0

In [8]:
df.iloc[0:2]  #here in slicing in iloc only 0,1 (2 rows) will be printed where 2 is excluded here

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0

CONDITIONAL FILTERING OR BOOLEAN FILTERING

In [10]:
#Age of people which is greater than 40 
df[df["Age"]>40]   #To get the entire dataframe we should give it inside [] brackets

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
6,200006,0,59.0,Self Enquiry,1,9.0,Small Business,Female,2,2.0,Basic,5.0,Divorced,5.0,1,2,1,1.0,Executive,17670.0
18,200018,0,53.0,Self Enquiry,3,8.0,Salaried,Female,3,4.0,Super Deluxe,3.0,Divorced,3.0,0,3,1,0.0,AVP,30427.0
25,200025,0,53.0,Self Enquiry,1,11.0,Salaried,Female,2,3.0,King,3.0,Married,5.0,0,5,0,1.0,VP,34094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,204876,1,52.0,Self Enquiry,3,34.0,Salaried,Male,3,4.0,Deluxe,3.0,Single,3.0,1,5,1,2.0,Manager,32704.0
4880,204880,1,59.0,Self Enquiry,1,28.0,Small Business,Female,4,4.0,Deluxe,4.0,Married,6.0,0,3,1,2.0,Manager,28686.0
4881,204881,1,41.0,Self Enquiry,2,25.0,Salaried,Male,3,2.0,Basic,5.0,Married,2.0,0,1,1,2.0,Executive,21065.0
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0

In [9]:
df["Age"]>40   #If we do not give it inside the [] brackets, we will only get whether it is true or false and not the entire dataframe

0        True
1        True
2       False
3       False
4       False
        ...
4883     True
4884    False
4885     True
4886    False
4887    False
Name: Age, Length: 4888, dtype: bool

In [12]:
#Filtering using 2 conditions - Age and CityTier
df[(df["Age"]<35) & (df["CityTier"]==1)]

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0
7,200007,0,30.0,Self Enquiry,1,30.0,Salaried,Male,3,3.0,Basic,3.0,Married,2.0,0,2,0,1.0,Executive,17693.0
12,200012,0,31.0,Self Enquiry,1,32.0,Salaried,Male,2,3.0,Basic,3.0,Married,2.0,0,3,0,1.0,Executive,17911.0
13,200013,0,34.0,Self Enquiry,1,25.0,Small Business,Male,3,3.0,Basic,3.0,Married,1.0,0,3,0,2.0,Executive,17661.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4849,204849,1,33.0,Company Invited,1,10.0,Salaried,Fe Male,3,4.0,Basic,3.0,Unmarried,3.0,0,4,1,1.0,Executive,24887.0
4853,204853,1,33.0,Self Enquiry,1,9.0,Small Business,Male,3,4.0,Deluxe,4.0,Married,6.0,0,4,1,2.0,Manager,23561.0
4858,204858,1,29.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,5.0,Unmarried,5.0,1,3,0,3.0,Executive,25352.0
4862,204862,1,31.0,Self Enquiry,1,9.0,Salaried,Male,4,4.0,Basic,4.0,Single,3.0,0,3,0,1.0,Executive,30594.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0

In [19]:
#Filtering using age,gender and occupation at same time
df[(df["Age"]>=25) & (df["Age"]<=40) & (df["Gender"]=="Male") & (df["Occupation"]=="Salaried")]

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0
7,200007,0,30.0,Self Enquiry,1,30.0,Salaried,Male,3,3.0,Basic,3.0,Married,2.0,0,2,0,1.0,Executive,17693.0
8,200008,0,38.0,Company Invited,1,29.0,Salaried,Male,2,4.0,Standard,3.0,Unmarried,1.0,0,3,0,0.0,Senior Manager,24526.0
12,200012,0,31.0,Self Enquiry,1,32.0,Salaried,Male,2,3.0,Basic,3.0,Married,2.0,0,3,0,1.0,Executive,17911.0
14,200014,1,28.0,Self Enquiry,1,30.0,Salaried,Male,2,4.0,Basic,3.0,Single,6.0,1,2,0,0.0,Executive,17028.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4864,204864,1,32.0,Self Enquiry,2,29.0,Salaried,Male,3,6.0,Basic,3.0,Married,3.0,0,1,0,2.0,Executive,28530.0
4877,204877,1,39.0,Company Invited,1,16.0,Salaried,Male,4,4.0,Deluxe,5.0,Married,6.0,0,3,0,3.0,Manager,25571.0
4882,204882,1,37.0,Self Enquiry,2,20.0,Salaried,Male,3,5.0,Basic,5.0,Married,6.0,1,5,1,2.0,Executive,23317.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

SORTING OF DATAS
The raw datas will not be arranged in any order properly. So we need to sort it either in asc or desc order
asc --> Lower - Higher
desc--> Higher - Lower

Sort_values(by) is a method in the dataframe that holds a default parameter called as 'by' where we should give the column name by which it should be sorted.

In [12]:
df.sort_values(by="Age")
#or
df.sort_values("Age")   #This gives the output of age that is sorted in ascending order by default.

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
828,200828,1,18.0,Company Invited,1,14.0,Small Business,Male,3,3.0,Basic,3.0,Single,2.0,0,5,0,0.0,Executive,16904.0
727,200727,0,18.0,Company Invited,1,11.0,Salaried,Male,3,3.0,Basic,3.0,Single,2.0,0,2,1,1.0,Executive,16051.0
2442,202442,1,18.0,Self Enquiry,3,15.0,Small Business,Male,2,3.0,Basic,3.0,Single,2.0,0,5,0,1.0,Executive,16611.0
972,200972,0,18.0,Company Invited,1,6.0,Salaried,Female,3,3.0,Basic,3.0,Single,2.0,0,5,1,1.0,Executive,16611.0
2298,202298,1,18.0,Company Invited,1,14.0,Small Business,Male,3,3.0,Basic,3.0,Single,2.0,0,5,1,0.0,Executive,16904.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,202410,1,NaN,Self Enquiry,1,30.0,Small Business,Male,2,3.0,Basic,4.0,Married,2.0,1,1,0,0.0,Executive,NaN
2413,202413,1,NaN,Self Enquiry,3,21.0,Small Business,Male,2,5.0,Deluxe,3.0,Married,7.0,1,1,0,1.0,Manager,18423.0
2427,202427,1,NaN,Self Enquiry,3,22.0,Small Business,Male,3,3.0,Standard,3.0,Married,3.0,0,5,0,1.0,Senior Manager,18544.0
2430,202430,1,NaN,Self Enquiry,1,14.0,Small Business,Female,3,3.0,Basic,5.0,Married,2.0,1,3,0,2.0,Executive,NaN
2435,202435,1,NaN,Self Enquiry,2,26.0,Small Business,Female,3,3.0,Basic,4.0,Married,1.0,1,3,0,1.0,Executive,18669.0

In [21]:
#def sort_values(by, ascending=True) --> default parameter=True 
df.sort_values("Age", ascending=False)  _#Here we gave false, and hence the age will be sorted in desc order.

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
3653,203653,0,61.0,Self Enquiry,1,7.0,Small Business,Male,4,6.0,Standard,3.0,Married,5.0,0,5,0,1.0,Senior Manager,29561.0
4793,204793,0,61.0,Self Enquiry,3,14.0,Small Business,Male,3,2.0,Deluxe,3.0,Married,2.0,1,5,0,1.0,Manager,23898.0
2855,202855,0,61.0,Self Enquiry,1,14.0,Salaried,Female,3,4.0,King,5.0,Divorced,7.0,0,5,0,1.0,VP,38244.0
2871,202871,0,61.0,Company Invited,3,35.0,Small Business,Female,4,5.0,Standard,5.0,Divorced,6.0,0,2,1,1.0,Senior Manager,28944.0
3323,203323,0,61.0,Self Enquiry,3,14.0,Small Business,Male,3,2.0,Deluxe,3.0,Married,2.0,1,5,0,1.0,Manager,23898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,202410,1,NaN,Self Enquiry,1,30.0,Small Business,Male,2,3.0,Basic,4.0,Married,2.0,1,1,0,0.0,Executive,NaN
2413,202413,1,NaN,Self Enquiry,3,21.0,Small Business,Male,2,5.0,Deluxe,3.0,Married,7.0,1,1,0,1.0,Manager,18423.0
2427,202427,1,NaN,Self Enquiry,3,22.0,Small Business,Male,3,3.0,Standard,3.0,Married,3.0,0,5,0,1.0,Senior Manager,18544.0
2430,202430,1,NaN,Self Enquiry,1,14.0,Small Business,Female,3,3.0,Basic,5.0,Married,2.0,1,3,0,2.0,Executive,NaN
2435,202435,1,NaN,Self Enquiry,2,26.0,Small Business,Female,3,3.0,Basic,4.0,Married,1.0,1,3,0,1.0,Executive,18669.0

MISSING VALUES
We cannot ignore missing datas and analyze the dataset as it is. If we do so, the conclusion will not be correct. So handling the missing values is very important.

In [15]:
#First we have to check whether there is any missing values present in the dataset, by using isnull() which is a method.
df.isnull()  #Gives True or False (If True-->missing value, False-->Data is present)

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4884,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4885,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4886,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
df.isnull().sum()  #sum() Gives the count of missing values for each columns completely.

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64