STATISTICS
Statistics is the branch of applied mathematics that deals with collecting, organizing, analyzing, interpreting and presenting the data.
Satistics is of two types:
1.Descriptive statistics
2.Inferential statistics

Desciptive statistics : By using the factual data, the calculation will be done
Eg: Avg salary of employees working in a company (Factual data)

Inferential statistics : By assuming the data to be, we will calculate on the datas
Eg: Avg salary of all Data Analyst working in India (Only assumptions can be done)
EXIT POLLS : only 20 - 30% of the datas will be collected and assumption will be done that who will win the election

In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\employees.csv")
print(df)

     emp_id  dept_id           name department       city  education  \
0      1001        3   Rahul Sharma         HR  Hyderabad    Masters
1      1002        4  Karthik Kumar  Marketing  Bangalore    Diploma
2      1003        2  Karthik Reddy       Tech  Bangalore    Masters
3      1004        2  Lakshmi Kumar       Tech    Chennai  Bachelors
4      1005        3   Arjun Sharma         HR  Hyderabad    Masters
..      ...      ...            ...        ...        ...        ...
196    1197        1    Suresh Iyer      Sales    Chennai    Diploma
197    1198        2      Deepa Rao       Tech    Chennai    Diploma
198    1199        1    Rahul Kumar      Sales  Hyderabad  Bachelors
199    1200        2    Kavya Singh       Tech    Chennai    Masters
200    1021        1    Anita Patel      Sales       Pune    Masters

        rating  experience   age  height_cm     salary   join_date
0         Poor           4  53.0      169.5    47764.0  2018-01-03
1         Poor          13  57.0      169.5    86052.0  2024-07-02
2         Good           1  56.0      166.5    62990.0  2025-03-04
3    Excellent          11  41.0      175.3  5200000.0  2022-10-15
4    Excellent           9  42.0      173.0    62556.0  2022-05-20
..         ...         ...   ...        ...        ...         ...
196       Good           5  42.0      173.8    51904.0  2023-07-21
197       Poor           9  43.0      163.0    89980.0  2024-11-21
198       Poor          13  58.0      168.0    78169.0  2015-11-01
199    Average           5  47.0      168.1    66075.0  2024-02-05
200    Average           5  51.0      171.7    59760.0  2025-06-05

[201 rows x 12 columns]

In [10]:
df["salary"]

0        47764.0
1        86052.0
2        62990.0
3      5200000.0
4        62556.0
         ...
196      51904.0
197      89980.0
198      78169.0
199      66075.0
200      59760.0
Name: salary, Length: 201, dtype: float64

In [30]:
print(df["salary"].mean())
print(df["salary"].median())
print(df["salary"].std())
print(df["salary"].min())
print(df["salary"].max())
print(df["salary"].quantile(0.25))
print(df["salary"].quantile(0.50))
print(df["salary"].quantile(0.75))

95648.40703517589
68647.0
364031.9045104082
33085.0
5200000.0
59003.5
68647.0
80599.5

In [39]:
print(df["department"].value_counts())
print(df["dept_id"].mean())
print(round(df["dept_id"].mean(),2))

department
Sales        65
Tech         49
HR           45
Marketing    42
Name: count, dtype: int64
2.318407960199005
2.32

In [40]:
df["salary"]>80000

0      False
1       True
2      False
3       True
4      False
       ...
196    False
197     True
198    False
199    False
200    False
Name: salary, Length: 201, dtype: bool

In [41]:
df[df["salary"]>80000]

,emp_id,dept_id,name,department,city,education,rating,experience,age,height_cm,salary,join_date
1,1002,4,Karthik Kumar,Marketing,Bangalore,Diploma,Poor,13,57.0,169.5,86052.0,2024-07-02
3,1004,2,Lakshmi Kumar,Tech,Chennai,Bachelors,Excellent,11,41.0,175.3,5200000.0,2022-10-15
10,1011,1,Rohit Kumar,Sales,Chennai,Bachelors,Good,15,57.0,163.6,85285.0,2020-03-23
11,1012,1,Rahul Rao,Sales,Pune,Bachelors,Excellent,14,27.0,159.8,92642.0,2022-11-13
15,1016,3,Ramesh Nair,HR,Hyderabad,Diploma,Poor,15,54.0,163.8,80039.0,2019-11-28
21,1022,2,Priya Singh,Tech,Chennai,Bachelors,Average,0,34.0,169.9,88840.0,2015-05-07
31,1032,2,Kavya Rao,Tech,Chennai,Masters,Excellent,13,41.0,158.3,105413.0,2016-05-02
32,1033,2,Ramesh Sharma,Tech,Hyderabad,Diploma,Average,13,25.0,164.1,103136.0,2019-02-15
34,1035,2,Pooja Nair,Tech,Hyderabad,Bachelors,Average,6,38.0,163.3,91537.0,2020-01-09
36,1037,4,Deepa Nair,Marketing,Hyderabad,Diploma,Average,12,46.0,166.7,87585.0,2020-01-27
38,1039,2,Kavya Menon,Tech,Bangalore,Bachelors,Good,9,42.0,169.4,93031.0,2023-06-08
44,1045,2,Suresh Singh,Tech,Bangalore,Masters,Poor,15,51.0,176.8,101639.0,2019-02-28
48,1049,1,Pooja Menon,Sales,Hyderabad,Bachelors,Average,15,34.0,169.0,92415.0,2016-10-03
49,1050,2,Pooja Iyer,Tech,Bangalore,Masters,Good,8,35.0,166.8,89590.0,2022-08-13
51,1052,1,Divya Sharma,Sales,Chennai,Masters,Poor,10,39.0,168.1,85000.0,2019-06-03
52,1053,4,Manoj Rao,Marketing,Hyderabad,Diploma,Good,12,27.0,167.9,92004.0,2015-11-10
53,1054,2,Sneha Nair,Tech,Hyderabad,Bachelors,Poor,7,46.0,166.5,91976.0,2023-09-07
56,1057,2,Sanjay Singh,Tech,Chennai,Bachelors,Good,5,49.0,172.3,86944.0,2021-03-18
57,1058,2,Suresh Gupta,Tech,Chennai,Bachelors,Good,7,57.0,171.9,89432.0,2018-01-24
60,1061,4,Pooja Menon,Marketing,Pune,Diploma,Poor,15,35.0,168.0,96471.0,2017-03-17
61,1062,1,Ramesh Reddy,Sales,Chennai,Masters,Poor,14,40.0,175.1,93417.0,2017-11-09
63,1064,4,Arjun Menon,Marketing,Chennai,Masters,Average,8,22.0,165.1,82516.0,2021-12-21
69,1070,4,Priya Kumar,Marketing,Bangalore,Bachelors,Poor,11,43.0,167.2,87184.0,2021-02-18
70,1071,2,Karthik Sharma,Tech,Bangalore,Masters,Excellent,12,33.0,179.6,84623.0,2020-09-15
79,1080,2,Meena Kumar,Tech,Bangalore,Diploma,Excellent,7,35.0,165.0,80057.0,2022-06-02
83,1084,4,Divya Singh,Marketing,Chennai,Masters,Poor,15,31.0,169.4,91336.0,2021-12-09
85,1086,4,Vikram Rao,Marketing,Bangalore,Diploma,Excellent,12,57.0,168.8,80280.0,2020-08-25
86,1087,2,Divya Sharma,Tech,Hyderabad,Masters,Average,4,30.0,168.9,86348.0,2020-05-06
91,1092,4,Sanjay Menon,Marketing,Chennai,Bachelors,Excellent,14,NaN,168.6,85326.0,2022-07-04
94,1095,2,Kavya Reddy,Tech,Hyderabad,Masters,Good,7,50.0,171.0,90168.0,2017-05-17
98,1099,1,Mahesh Iyer,Sales,Hyderabad,Bachelors,Good,14,21.0,179.0,81555.0,2015-04-05
115,1116,1,Priya Gupta,Sales,Hyderabad,Diploma,Excellent,15,46.0,156.0,85782.0,2016-07-21
124,1125,2,Sanjay Sharma,Tech,Bangalore,Bachelors,Average,10,31.0,160.2,91572.0,2018-09-12
127,1128,1,Manoj Patel,Sales,Hyderabad,Diploma,Average,13,40.0,162.3,88420.0,2021-09-08
128,1129,4,Suresh Nair,Marketing,Pune,Masters,Average,14,30.0,172.1,86119.0,2020-11-21
129,1130,4,Anita Menon,Marketing,Hyderabad,Diploma,Good,14,45.0,167.7,100198.0,2025-05-14
130,1131,2,Kavya Gupta,Tech,Chennai,Masters,Good,15,41.0,168.2,116894.0,2022-08-14
133,1134,2,Vikram Patel,Tech,Bangalore,Masters,Good,6,33.0,160.0,93133.0,2022-12-07
135,1136,4,Arjun Menon,Marketing,Chennai,Masters,Poor,14,31.0,161.0,96580.0,2020-08-23
143,1144,2,Rohit Reddy,Tech,Pune,Diploma,Good,9,22.0,165.6,81069.0,2021-10-21
144,1145,1,Priya Rao,Sales,Pune,Bachelors,Poor,15,21.0,167.1,80174.0,2025-07-20
145,1146,2,Suresh Menon,Tech,Chennai,Diploma,Poor,15,48.0,158.0,103915.0,2015-01-22
153,1154,4,Arjun Iyer,Marketing,Bangalore,Masters,Excellent,12,50.0,180.7,84593.0,2018-05-19
155,1156,2,Rohit Gupta,Tech,Hyderabad,Bachelors,Average,6,36.0,171.4,80919.0,2015-08-12
158,1159,2,Vikram Rao,Tech,Bangalore,Diploma,Poor,8,23.0,161.9,89548.0,2023-06-28
159,1160,4,Suresh Patel,Marketing,Pune,Diploma,Poor,15,37.0,162.3,106170.0,2020-10-08
160,1161,1,Manoj Nair,Sales,Chennai,Diploma,Poor,12,37.0,182.2,82193.0,2020-01-18
170,1171,2,Arjun Reddy,Tech,Chennai,Masters,Poor,4,26.0,159.9,81050.0,2024-12-16
173,1174,2,Lakshmi Patel,Tech,Bangalore,Bachelors,Excellent,11,54.0,170.8,106139.0,2016-02-12
174,1175,2,Lakshmi Kumar,Tech,Hyderabad,Diploma,Excellent,10,49.0,152.2,93296.0,2023-01-17
178,1179,2,Divya Reddy,Tech,Bangalore,Masters,Excellent,7,47.0,176.3,89564.0,2024-10-17
184,1185,2,Rohit Rao,Tech,Hyderabad,Bachelors,Average,14,26.0,171.0,103400.0,2023-05-27
193,1194,2,Ramesh Kumar,Tech,Bangalore,Bachelors,Excellent,10,40.0,176.1,92687.0,2023-05-18
197,1198,2,Deepa Rao,Tech,Chennai,Diploma,Poor,9,43.0,163.0,89980.0,2024-11-21

In [42]:
df[(df["salary"]>80000) & (df["department"]=="Tech")]

,emp_id,dept_id,name,department,city,education,rating,experience,age,height_cm,salary,join_date
3,1004,2,Lakshmi Kumar,Tech,Chennai,Bachelors,Excellent,11,41.0,175.3,5200000.0,2022-10-15
21,1022,2,Priya Singh,Tech,Chennai,Bachelors,Average,0,34.0,169.9,88840.0,2015-05-07
31,1032,2,Kavya Rao,Tech,Chennai,Masters,Excellent,13,41.0,158.3,105413.0,2016-05-02
32,1033,2,Ramesh Sharma,Tech,Hyderabad,Diploma,Average,13,25.0,164.1,103136.0,2019-02-15
34,1035,2,Pooja Nair,Tech,Hyderabad,Bachelors,Average,6,38.0,163.3,91537.0,2020-01-09
38,1039,2,Kavya Menon,Tech,Bangalore,Bachelors,Good,9,42.0,169.4,93031.0,2023-06-08
44,1045,2,Suresh Singh,Tech,Bangalore,Masters,Poor,15,51.0,176.8,101639.0,2019-02-28
49,1050,2,Pooja Iyer,Tech,Bangalore,Masters,Good,8,35.0,166.8,89590.0,2022-08-13
53,1054,2,Sneha Nair,Tech,Hyderabad,Bachelors,Poor,7,46.0,166.5,91976.0,2023-09-07
56,1057,2,Sanjay Singh,Tech,Chennai,Bachelors,Good,5,49.0,172.3,86944.0,2021-03-18
57,1058,2,Suresh Gupta,Tech,Chennai,Bachelors,Good,7,57.0,171.9,89432.0,2018-01-24
70,1071,2,Karthik Sharma,Tech,Bangalore,Masters,Excellent,12,33.0,179.6,84623.0,2020-09-15
79,1080,2,Meena Kumar,Tech,Bangalore,Diploma,Excellent,7,35.0,165.0,80057.0,2022-06-02
86,1087,2,Divya Sharma,Tech,Hyderabad,Masters,Average,4,30.0,168.9,86348.0,2020-05-06
94,1095,2,Kavya Reddy,Tech,Hyderabad,Masters,Good,7,50.0,171.0,90168.0,2017-05-17
124,1125,2,Sanjay Sharma,Tech,Bangalore,Bachelors,Average,10,31.0,160.2,91572.0,2018-09-12
130,1131,2,Kavya Gupta,Tech,Chennai,Masters,Good,15,41.0,168.2,116894.0,2022-08-14
133,1134,2,Vikram Patel,Tech,Bangalore,Masters,Good,6,33.0,160.0,93133.0,2022-12-07
143,1144,2,Rohit Reddy,Tech,Pune,Diploma,Good,9,22.0,165.6,81069.0,2021-10-21
145,1146,2,Suresh Menon,Tech,Chennai,Diploma,Poor,15,48.0,158.0,103915.0,2015-01-22
155,1156,2,Rohit Gupta,Tech,Hyderabad,Bachelors,Average,6,36.0,171.4,80919.0,2015-08-12
158,1159,2,Vikram Rao,Tech,Bangalore,Diploma,Poor,8,23.0,161.9,89548.0,2023-06-28
170,1171,2,Arjun Reddy,Tech,Chennai,Masters,Poor,4,26.0,159.9,81050.0,2024-12-16
173,1174,2,Lakshmi Patel,Tech,Bangalore,Bachelors,Excellent,11,54.0,170.8,106139.0,2016-02-12
174,1175,2,Lakshmi Kumar,Tech,Hyderabad,Diploma,Excellent,10,49.0,152.2,93296.0,2023-01-17
178,1179,2,Divya Reddy,Tech,Bangalore,Masters,Excellent,7,47.0,176.3,89564.0,2024-10-17
184,1185,2,Rohit Rao,Tech,Hyderabad,Bachelors,Average,14,26.0,171.0,103400.0,2023-05-27
193,1194,2,Ramesh Kumar,Tech,Bangalore,Bachelors,Excellent,10,40.0,176.1,92687.0,2023-05-18
197,1198,2,Deepa Rao,Tech,Chennai,Diploma,Poor,9,43.0,163.0,89980.0,2024-11-21

In [46]:
print(df[df["salary"]>80000].value_counts())

emp_id  dept_id  name            department  city       education  rating     experience  age   height_cm  salary     join_date
1002    4        Karthik Kumar   Marketing   Bangalore  Diploma    Poor       13          57.0  169.5      86052.0    2024-07-02    1
1004    2        Lakshmi Kumar   Tech        Chennai    Bachelors  Excellent  11          41.0  175.3      5200000.0  2022-10-15    1
1011    1        Rohit Kumar     Sales       Chennai    Bachelors  Good       15          57.0  163.6      85285.0    2020-03-23    1
1012    1        Rahul Rao       Sales       Pune       Bachelors  Excellent  14          27.0  159.8      92642.0    2022-11-13    1
1016    3        Ramesh Nair     HR          Hyderabad  Diploma    Poor       15          54.0  163.8      80039.0    2019-11-28    1
1022    2        Priya Singh     Tech        Chennai    Bachelors  Average    0           34.0  169.9      88840.0    2015-05-07    1
1032    2        Kavya Rao       Tech        Chennai    Masters    Excellent  13          41.0  158.3      105413.0   2016-05-02    1
1033    2        Ramesh Sharma   Tech        Hyderabad  Diploma    Average    13          25.0  164.1      103136.0   2019-02-15    1
1035    2        Pooja Nair      Tech        Hyderabad  Bachelors  Average    6           38.0  163.3      91537.0    2020-01-09    1
1037    4        Deepa Nair      Marketing   Hyderabad  Diploma    Average    12          46.0  166.7      87585.0    2020-01-27    1
1039    2        Kavya Menon     Tech        Bangalore  Bachelors  Good       9           42.0  169.4      93031.0    2023-06-08    1
1045    2        Suresh Singh    Tech        Bangalore  Masters    Poor       15          51.0  176.8      101639.0   2019-02-28    1
1049    1        Pooja Menon     Sales       Hyderabad  Bachelors  Average    15          34.0  169.0      92415.0    2016-10-03    1
1050    2        Pooja Iyer      Tech        Bangalore  Masters    Good       8           35.0  166.8      89590.0    2022-08-13    1
1052    1        Divya Sharma    Sales       Chennai    Masters    Poor       10          39.0  168.1      85000.0    2019-06-03    1
1053    4        Manoj Rao       Marketing   Hyderabad  Diploma    Good       12          27.0  167.9      92004.0    2015-11-10    1
1054    2        Sneha Nair      Tech        Hyderabad  Bachelors  Poor       7           46.0  166.5      91976.0    2023-09-07    1
1057    2        Sanjay Singh    Tech        Chennai    Bachelors  Good       5           49.0  172.3      86944.0    2021-03-18    1
1058    2        Suresh Gupta    Tech        Chennai    Bachelors  Good       7           57.0  171.9      89432.0    2018-01-24    1
1061    4        Pooja Menon     Marketing   Pune       Diploma    Poor       15          35.0  168.0      96471.0    2017-03-17    1
1062    1        Ramesh Reddy    Sales       Chennai    Masters    Poor       14          40.0  175.1      93417.0    2017-11-09    1
1064    4        Arjun Menon     Marketing   Chennai    Masters    Average    8           22.0  165.1      82516.0    2021-12-21    1
1070    4        Priya Kumar     Marketing   Bangalore  Bachelors  Poor       11          43.0  167.2      87184.0    2021-02-18    1
1071    2        Karthik Sharma  Tech        Bangalore  Masters    Excellent  12          33.0  179.6      84623.0    2020-09-15    1
1080    2        Meena Kumar     Tech        Bangalore  Diploma    Excellent  7           35.0  165.0      80057.0    2022-06-02    1
1084    4        Divya Singh     Marketing   Chennai    Masters    Poor       15          31.0  169.4      91336.0    2021-12-09    1
1086    4        Vikram Rao      Marketing   Bangalore  Diploma    Excellent  12          57.0  168.8      80280.0    2020-08-25    1
1087    2        Divya Sharma    Tech        Hyderabad  Masters    Average    4           30.0  168.9      86348.0    2020-05-06    1
1095    2        Kavya Reddy     Tech        Hyderabad  Masters    Good       7           50.0  171.0      90168.0    2017-05-17    1
1099    1        Mahesh Iyer     Sales       Hyderabad  Bachelors  Good       14          21.0  179.0      81555.0    2015-04-05    1
1116    1        Priya Gupta     Sales       Hyderabad  Diploma    Excellent  15          46.0  156.0      85782.0    2016-07-21    1
1125    2        Sanjay Sharma   Tech        Bangalore  Bachelors  Average    10          31.0  160.2      91572.0    2018-09-12    1
1128    1        Manoj Patel     Sales       Hyderabad  Diploma    Average    13          40.0  162.3      88420.0    2021-09-08    1
1129    4        Suresh Nair     Marketing   Pune       Masters    Average    14          30.0  172.1      86119.0    2020-11-21    1
1130    4        Anita Menon     Marketing   Hyderabad  Diploma    Good       14          45.0  167.7      100198.0   2025-05-14    1
1131    2        Kavya Gupta     Tech        Chennai    Masters    Good       15          41.0  168.2      116894.0   2022-08-14    1
1134    2        Vikram Patel    Tech        Bangalore  Masters    Good       6           33.0  160.0      93133.0    2022-12-07    1
1136    4        Arjun Menon     Marketing   Chennai    Masters    Poor       14          31.0  161.0      96580.0    2020-08-23    1
1144    2        Rohit Reddy     Tech        Pune       Diploma    Good       9           22.0  165.6      81069.0    2021-10-21    1
1145    1        Priya Rao       Sales       Pune       Bachelors  Poor       15          21.0  167.1      80174.0    2025-07-20    1
1146    2        Suresh Menon    Tech        Chennai    Diploma    Poor       15          48.0  158.0      103915.0   2015-01-22    1
1154    4        Arjun Iyer      Marketing   Bangalore  Masters    Excellent  12          50.0  180.7      84593.0    2018-05-19    1
1156    2        Rohit Gupta     Tech        Hyderabad  Bachelors  Average    6           36.0  171.4      80919.0    2015-08-12    1
1159    2        Vikram Rao      Tech        Bangalore  Diploma    Poor       8           23.0  161.9      89548.0    2023-06-28    1
1160    4        Suresh Patel    Marketing   Pune       Diploma    Poor       15          37.0  162.3      106170.0   2020-10-08    1
1161    1        Manoj Nair      Sales       Chennai    Diploma    Poor       12          37.0  182.2      82193.0    2020-01-18    1
1171    2        Arjun Reddy     Tech        Chennai    Masters    Poor       4           26.0  159.9      81050.0    2024-12-16    1
1174    2        Lakshmi Patel   Tech        Bangalore  Bachelors  Excellent  11          54.0  170.8      106139.0   2016-02-12    1
1175    2        Lakshmi Kumar   Tech        Hyderabad  Diploma    Excellent  10          49.0  152.2      93296.0    2023-01-17    1
1179    2        Divya Reddy     Tech        Bangalore  Masters    Excellent  7           47.0  176.3      89564.0    2024-10-17    1
1185    2        Rohit Rao       Tech        Hyderabad  Bachelors  Average    14          26.0  171.0      103400.0   2023-05-27    1
1194    2        Ramesh Kumar    Tech        Bangalore  Bachelors  Excellent  10          40.0  176.1      92687.0    2023-05-18    1
1198    2        Deepa Rao       Tech        Chennai    Diploma    Poor       9           43.0  163.0      89980.0    2024-11-21    1
Name: count, dtype: int64

In [48]:
print(round(df.groupby("department")["salary"].mean()),2)

department
HR            56705.0
Marketing     73954.0
Sales         66535.0
Tech         189754.0
Name: salary, dtype: float64 2

In [53]:
print(df["salary"].mean())
print(df["dept_id"].mean())

95648.40703517589
2.318407960199005

Actually in the above cell how did we got the average value in float for the dept_id column.
If any column is taken from the table we should first understand what type of data is present in the column and then we should perform the operation
based on the data. Eg: min,max,mean,median,std,count,<50000,>50000 everything can be done on the salary column. But it cannot be done on the city column.

Data - Piece of information
2 Types - Quantitative and Qualitative

Quantitative - Measures or counts the variables using numerical values
Qualitative - Describes the qualities or categories uding words or names.

Quantitaive data is of 2 types
Discrete - countable --> In a family there are 2 children, we cannot say 2.5 children
continuous - eg: Height --> Can contain any values in between, we can say that height of a person in 176.5 cm

TYPES OF DATA - Nominal, Ordinal, Interval ,Ratio

In [54]:
#Nominal
df["department"].value_counts() 
#Automatically getting sorted based on the count. Any type of data where order doesnt matter is Nominal data

department
Sales        65
Tech         49
HR           45
Marketing    42
Name: count, dtype: int64

In [55]:
#Ordinal
df["rating"].value_counts()
#But here we can order the ratings like Excellent->Good->Average->Poor
#we can order them but we dont know whats the interval between them for categorizing.This cannot be understood by computer but humans can

rating
Poor         58
Good         51
Excellent    49
Average      43
Name: count, dtype: int64

#Interval - 0 doesn't mean anything here
Today 15 degree celcius, tomorrow 30 degree celcius
15 - 59F
30 - 86F  but it shoul be actually 59*2 = 118D
In Interval type of datas, there will be interval but it is not maintained properlt.

#Ratio - 0 makes sense here.
There will be interval and it literally makes sense. Equally distributed on a particular order.
Person A earns 10000
Person B earns 20000
We say that Person B earns twice the Person A. This type of data is Ratio.

POPULATION

Getting all the actual datas
Eg : ALL students of TAP Academy
What we fetch from Population is called as PARAMETER

SAMPLE DATA - Taking a small sample and assuming it would be equivalent to the answer

Subset of a population is sample data
Eg : Only certain batches of TAP Academy
What we fetch from sample data is called as STATISTIC

TWO more terminologies to understand :
1.Random Sampling - A probability method where a researcher picks a subset of individuals from a larger group so that every individual gets an equal and exact chance of being chosen.
2.Bias - Biased towards one type of data but we cannot say it's correct or wrong.

SAMPLE has two types of sample:
1. Probability sample  --> 4 types - simple random sampling, systematic sampling, stratified sampling, clusterd sampling
2. Non Probability Sample

In [59]:
#1.Simple random sampling:
for seed in [1,2,3,4,5]:
    rand=df.sample(30,random_state=seed)
    print(seed, rand['salary'].mean())
print("Mean: ", df['salary'].mean())   
#when the same seed 1 is given, the same 30 random employees will be got.

1 69768.76666666666
2 243614.66666666666
3 239974.93333333332
4 69570.2
5 238963.96666666667
Mean:  95648.40703517589

In [67]:
#Instead of picking 5 random seeds with 30 employees each, we can show favourism here(Bias)
small = df.nsmallest(5, "salary")
print("mean :", small["salary"].mean())

mean : 36313.2

#2.Systematic sampling - Order is followed here.
out of 2000 products 200 products have to be picked and mean of those products will be found. 
2000/200 = 10. So 1,11,21,31,41 these ways products will be picked till 2000.
10 machines are there. If 1 machine produces 1 products and all 1,11,21,31,41 belongs to machine 1, so systematic sampling fails here.

In [ ]:
#Stratified sampling
Total staffs-2000. Tech - 1200, Sales-500, HR- 300. We have to pick 200 out of them.
It might randomply pick the same department employees again and again. To avoid that,
Tech - 1200/2000 = 0.6 = 60%,similarly Sales = 25% and HR=15%

60% of 200 = 120, 25% of 200 =50, 15% of 200 = 30
Total we got 200 equally distributed for each department, so that we will get the answer accurate.

#Cluster Sampling:
staff-2000, cities - 40
40*5=2000 so in 1 city = 5 staffs. (Stratified here becomes more expensive) 
If in one city = 50 employees, then we can get 2000 staffs in 40 cities
To pick 200 employees, 4 cities alone is enough
In cluster, we will focus on which is convenient, easy and based on money. Instead of going to 40 cities, we will go only to 4 cities and pick 50 staffs in eac

NON PROBABLILITY SAMPLIMG is of 4 types
1. Convenience Sampling
2. Quoata Sampling
3. Judgemental Sampling
4. Snowball Sampling

Noise - Equally spread out, And it has the probability of being correct.
Bias - It is focused on a particular place, pretty close to each other. It's actually wrong but it's confident.
More amount of data doesn't means it's correct

More data fixes noise - election with 50k datas - accurate and correct
But it cannot fix bias - 2.4 million datas

So how many people do we actually need ? --> 1068 people shoulb be randomly picked
a country of 30 million people - 1068
a country with 1.4 billion people - 1068

In [4]:
#In nominal type of data instead of finding average, we can find the mode. No use in finding the average of dept_id.
print(df["dept_id"].mean())
print(df["dept_id"].mode())
print(df["dept_id"].mode() [0])   #Highest no.of students is in dept_id 1

2.318407960199005
0    1
Name: dept_id, dtype: int64
1

In [7]:
print(df["salary"].mean())
print(df["salary"].median())  #The diff is 27001 apart, in this case use median

95648.40703517589
68647.0

Three rules to use:
If the numbers are evenly spread - mean
If numbers are few extreme - median
For words/categories based columns - mode

In [15]:
#when the values are not equally distributed we cannot report the mean or median on its own, we have to find the spread.
#Spread - How far the values are from the average.
#To find the spread, range is used which takes two extreme vlues (max-min)
print(df["salary"].describe().round(2))
sal=df["salary"]
print(sal.max() - sal.min())
#This huge diff is because of that one person with 52 lakhs salary.

count        199.00
mean       95648.41
std       364031.90
min        33085.00
25%        59003.50
50%        68647.00
75%        80599.50
max      5200000.00
Name: salary, dtype: float64
5166915.0

In [19]:
#To overcome the above problem, we can use quantiles -->25%, 50%, 75%

q1=(sal.quantile(0.25))
print(q1)   #This means that 25% of the people are earning below 59003
q2=(sal.quantile(0.50)) 
print(q2)#This means that 50% of the people are earning below 68647 (Median that is 50%)
q3=(sal.quantile(0.75))
print(q3)#This means that 75% of the people are earning below 80599

59003.5
68647.0
80599.5

In [37]:
#Interquantile range = q3 - q1
iqr = q3 - q1
print(iqr)  

#This is the diff between range and IQR
#Range = 5166915, IQR = 21596 (Practically possible)

21596.0

Paring :
When it's evenly distributed, use Mean + Range (Both uses evey values and gets wreked by extremes)
When it extremely distributed, use Median + IQR (cares about positions and ignore's extremes)

In [29]:
#MEAN - MEDIAN = SKEW
print(sal.mean() - sal.median())
# 3 types of skew - positive, negative, neutral
#lopsided means curve

27001.407035175886

In [35]:
print(df["salary"].mean()-df["salary"].median())
print(sal.skew())  #Positive skew, this is because that one employee with 52 lakhs salary.

27001.407035175886
14.063749892731751

#Every problem will be sorted if we remove that one person called as OUTLIER. Should we remove them ?
If we dlt the outlier - problem gets fixed
or It may be a salary of CEO also where we cannot remove it.

WHY a value can be extreme ?
1.A mistake - fix it or remove
2.Real and it matters - the CEO earns 52 lakhs. Keep it and report the median, not mean
3.Real and it is to the point

You may remove a value - But not quiently. You should always ask, WHY?, What? and HOW MANY?

In [42]:
#Whenever we need to remove the outlier, we have to know the range. Anything outside the fence is called as outliers.
#Anything outside the fence gets flagged and can be removed immediately. --> BOX PLOT
lower_fence = q1 - 1.5 * iqr
upper_fence = q3 + 1.5 * iqr
print(lower_fence)
print(upper_fence)

26609.5
112993.5

In [45]:
print(df[(sal<lower_fence) | (sal>upper_fence)])  #2 outliers gets flagged

     emp_id  dept_id           name department     city  education     rating  \
3      1004        2  Lakshmi Kumar       Tech  Chennai  Bachelors  Excellent
130    1131        2    Kavya Gupta       Tech  Chennai    Masters       Good

     experience   age  height_cm     salary   join_date
3            11  41.0      175.3  5200000.0  2022-10-15
130          15  41.0      168.2   116894.0  2022-08-14

In [52]:
#Similarly on age column
age=df["age"]
q1,q3=age.quantile([0.25,0.75])
print(q1,q3)

iqr=q3-q1
print(iqr)

low=q1-1.5*iqr
upp=q3+1.5*iqr
print(low,upp)

print(df[(age<low) | (age>upp)])

#Age cannot be -4 and 210. These are fraud datas, and it should be removed.

28.0 47.0
19.0
-0.5 75.5
     emp_id  dept_id           name department       city education rating  \
150    1151        3   Aditya Gupta         HR  Bangalore   Diploma   Good
177    1178        2  Lakshmi Singh       Tech  Hyderabad   Diploma   Poor

     experience    age  height_cm   salary   join_date
150           1   -4.0      160.0  33085.0  2021-04-13
177           1  210.0      176.9  66049.0  2021-03-18

The same rule has been followed for the age column. It matters on which column we are following the box plot.
Salary can be real with 52 lakhs, but the age is not possible. 
 SO for SALARY - KEEP
 AND for AGE - FIX
Purely depends on the column whether to keep or to fix
"THE RULE FLAGS. YOU DECIDE !"

In [59]:
#Both range and iqr falls between range so we will learn about std()
#STANDARD DEVIATION - spread of the salary column. It takes every single value and identifies the spread.
   # Only one person made it 22 times bigger than the actual std()
print(sal.std())

364031.9045104082

In [71]:
clean = sal[(sal>lower_fence) & (sal<upper_fence)]
print(clean)

0      47764.0
1      86052.0
2      62990.0
4      62556.0
5      47111.0
        ...
196    51904.0
197    89980.0
198    78169.0
199    66075.0
200    59760.0
Name: salary, Length: 197, dtype: float64

In [69]:
print(clean.mean())
print(sal.mean())

69630.14720812182
95648.40703517589

In [67]:
print(clean.std())
print(sal.std())    #This difference is because of that one person's salary

16066.088972779917
364031.9045104082

In [66]:
print(clean.median())
print(sal.median())

68342.0
68647.0

#How would you measure spread using every single values ?  --> MEan Absolute Deviation
Step 1 - For each value find out how far it's from the mean.
Step 2 - Remove the negative signs and make it absolute value, and find the average (spread)
This method is called as Mean absolute deviation, but almost nobody uses it.

One more way of doing this is,
In step 2- Square the values and fine the average. then it's called as Variance

We squared the value and got the variance. But what's the unit rupees square, doesnt makes any sense.
so we take square root of variance which is called as STANDARD DEVIATION. NOW rupees square - rupees

Standard Deviation depicts how much the values are deviated from the mean value, making use of every single value.

In [72]:
import numpy as np

print("Numpy: ", np.std(sal))  # Takes n(population)
print("Pandas: ", sal.std())  #Takes n-1 (Sample data)

Numpy:  363116.0995262202
Pandas:  364031.9045104082

In [73]:
print("Numpy: ", np.std(sal, ddof =1)) #Making numpy to take sample data. ddof=delta degree of freedom
#It's always better to use sample data, so if we set ddof=1 then it takes sample or defaulty it takes population in numpy

Numpy:  364031.9045104082